### ISSUE TITLE
Error when performing a command in tekkit

### ISSUE THREAD

**Issue by mikeyriver** [Multiverse/Multiverse-Core#1015]
Whenever i do a command such as /mv, i get this error:
 
[SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.3-AB
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
	at forge.bukkit.ForgeCommandMap.dispatch(ForgeCommandMap.java:55)
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:497)
	at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:843)
	at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:799)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:781)
	at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
	at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:474)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
	... 13 more
>

Its loads just fine however i cant access any of the commands of multiverse...
Note: im running it on a tekkit server 3.1.2

**Comment by TWSSYesterday** [comment]
No longer the case, ticket closed due to lack of updates on ticket.
