### ISSUE TITLE
World not importing!

### ISSUE THREAD

**Issue by TalTallon** [Multiverse/Multiverse-Core#1050]
Hi Folks,

I tried importing a world that I already have and it won't let me. Tried from the console too with the same error and issue

Any help appreciated

Thanks

Tallon

```
17:36:58 [INFO] TalTallon issued server command: /mv load Flatland
17:36:58 [SEVERE] java.lang.NullPointerException
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:408)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:383)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:359)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:346)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
17:36:58 [SEVERE]       at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
17:36:58 [SEVERE]       at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
17:36:58 [SEVERE]       at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
17:36:58 [SEVERE]       at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:887)
17:36:58 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
17:36:58 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
17:36:58 [SEVERE]       at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:510)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:980)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:898)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:853)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
17:36:58 [SEVERE]       at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
```

**Comment by TWSSYesterday** [comment]
Cannot replicated, locking due to inability to replicate and lack of updates.
