### ISSUE TITLE
Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-b654 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by WoodenAxe** [Multiverse/Multiverse-Core#1053]
```
23:04:20 [SEVERE] Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-b654
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at net.minecraft.server.v1_4_R1.PlayerList.changeDimension(PlayerList.java:451)
        at net.minecraft.server.v1_4_R1.EntityPlayer.b(EntityPlayer.java:345)
        at net.minecraft.server.v1_4_R1.Entity.y(Entity.java:276)
        at net.minecraft.server.v1_4_R1.EntityLiving.y(EntityLiving.java:319)
        at net.minecraft.server.v1_4_R1.Entity.j_(Entity.java:241)
        at net.minecraft.server.v1_4_R1.EntityLiving.j_(EntityLiving.java:518)
        at net.minecraft.server.v1_4_R1.EntityHuman.j_(EntityHuman.java:157)
        at net.minecraft.server.v1_4_R1.EntityPlayer.g(EntityPlayer.java:195)
        at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:354)
        at net.minecraft.server.v1_4_R1.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:115)
        at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:585)
        at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:481)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:416)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:304)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 23 more
```

**Comment by TWSSYesterday** [comment]
Not getting these errors any more on more recent builds.
