### ISSUE TITLE
/mv reload freezelags/drops everybody

### ISSUE THREAD

**Issue by OriginalMadman** [Multiverse/Multiverse-Core#1069]
Been running basically the same setup with MV core/portals/adventure for about a year with few or no hitches. I have been keeping pace with dev versions since the summer, and have been staying all on latest versions:

Core: b654
Portals: b672
Adventure: b657

This is an issue that I believe started with 1.4.6 or 1.4.7. AFAIK all MC versions before worked just fine.

Now, whenever /mv reload is done or an Adventure world reloads on the server, it freezelags everything and everyone drops out. Needless to say it is a little annoying (have several adventure worlds).

I went through all of the configs, and they seem fine.

Here is a log with stack trace:

2013-01-31 16:42:04 [INFO] OriginalMadman issued server command: /mv reload
2013-01-31 16:42:13 [INFO] [Multiverse-Core] 50 - World(s) loaded.
2013-01-31 16:42:33 [INFO] Read timed out
2013-01-31 16:42:55 [INFO] [MVPLogging] 94 - Portals(s) loaded
2013-01-31 16:42:56 [WARNING] [Server] The main thread failed to respond after 10 seconds
2013-01-31 16:42:56 [WARNING] [Server] Probable Plugin causes: 'Multiverse-Portals and Multiverse-Core'
2013-01-31 16:42:56 [WARNING] [Server] What follows is the stack trace of the main thread
2013-01-31 16:42:56 [WARNING] [Server]    at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:169)
2013-01-31 16:42:56 [WARNING] [Server]    at com.google.common.collect.ImmutableSet.copyFromCollection(ImmutableSet.java:361)
2013-01-31 16:42:56 [WARNING] [Server]    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:345)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.getDefaultPermissions(SimplePluginManager.java:580)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:150)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.craftbukkit.v1_4_R1.command.ServerCommandSender.recalculatePermissions(ServerCommandSender.java:57)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:615)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:603)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.recalculatePermissionDefaults(SimplePluginManager.java:596)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.removeFromUpperLists(MVPortal.java:423)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.removePermission(MVPortal.java:397)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.utils.PortalManager.removePortal(PortalManager.java:152)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.utils.PortalManager.removeAll(PortalManager.java:262)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MultiversePortals.reloadConfigs(MultiversePortals.java:384)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiversePortals.listeners.MVPCoreListener.configReload(MVPCoreListener.java:44)
2013-01-31 16:42:56 [WARNING] [Server]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-31 16:42:56 [WARNING] [Server]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-31 16:42:56 [WARNING] [Server]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-31 16:42:56 [WARNING] [Server]    at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiverseCore.commands.ReloadCommand.runCommand(ReloadCommand.java:49)
2013-01-31 16:42:56 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
2013-01-31 16:42:56 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
2013-01-31 16:42:56 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
2013-01-31 16:42:56 [WARNING] [Server]    at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:887)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2013-01-31 16:42:56 [WARNING] [Server]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerConnection.java:979)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.java:897)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:852)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:112)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
2013-01-31 16:42:56 [WARNING] [Server]    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
2013-01-31 16:42:56 [INFO] OriginalMadman lost connection: disconnect.endOfStream
2013-01-31 16:42:56 [INFO] MagicaDeHex lost connection: disconnect.endOfStream
2013-01-31 16:42:56 [INFO] Faua lost connection: disconnect.endOfStream
2013-01-31 16:42:56 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?

**Comment by TWSSYesterday** [comment]
MV Reload will of course hang for a while, however I cannot reproduce freezing on latest builds. Locked due to inactivity.
