### ISSUE TITLE
Multiverse throws error when using /mvgens

### ISSUE THREAD

**Issue by ThatBenderGuy** [Multiverse/Multiverse-Core#1103]
I get this error when I try to use /mvgens

```
17:12:33 [SEVERE] Plugin GroupManager v2.0 (2.9.6) (Phoenix) does not contain any generators that may be
used in the default world!
17:12:33 [INFO] [FlatlandsBuilder] Old configuration method detected converting to new configuration file
 method, please wait...
17:12:33 [SEVERE] Plugin VoxelSniper v5.168.5-SNAPSHOT-jnks196 does not contain any generators that may b
e used in the default world!
17:12:33 [SEVERE] Plugin Buycraft v5.2 does not contain any generators that may be used in the default wo
rld!
17:12:33 [SEVERE] Plugin Spout v1.4.7 b1416 does not contain any generators that may be used in the defau
lt world!
17:12:33 [SEVERE] Plugin BOSEconomy v0.7.3.1 does not contain any generators that may be used in the defa
ult world!
17:12:33 [SEVERE] Plugin Multiverse-Core v2.4-b527 does not contain any generators that may be used in th
e default world!
17:12:33 [SEVERE] Plugin CombatTag v5.6.1 does not contain any generators that may be used in the default
 world!
17:12:33 [SEVERE] Plugin Permissions v3.1.6 does not contain any generators that may be used in the defau
lt world!
17:12:33 [SEVERE] Plugin EpicBossRecoded v1.1.1 does not contain any generators that may be used in the d
efault world!
17:12:33 [SEVERE] Plugin ProtocolLib v2.2.0 does not contain any generators that may be used in the defau
lt world!
17:12:33 [SEVERE] Plugin Catacombs v2.9 does not contain any generators that may be used in the default w
orld!
17:12:33 [SEVERE] Plugin Essentials vPre2.10.1.4 does not contain any generators that may be used in the
default world!
17:12:33 [SEVERE] Plugin WorldEdit v5.5.1 does not contain any generators that may be used in the default
 world!
17:12:33 [SEVERE] Plugin EssentialsProtect vPre2.10.1.4 does not contain any generators that may be used
in the default world!
17:12:33 [SEVERE] Plugin EssentialsSpawn vPre2.10.1.4 does not contain any generators that may be used in
 the default world!
17:12:33 [SEVERE] Plugin Multiverse-Portals v2.4-b548 does not contain any generators that may be used in
 the default world!
17:12:33 [SEVERE] Plugin CommandBook v2.2 does not contain any generators that may be used in the default
 world!
17:12:33 [SEVERE] Plugin EssentialsAntiBuild vPre2.10.1.4 does not contain any generators that may be use
d in the default world!
17:12:33 [SEVERE] Plugin WorldGuard v5.7 does not contain any generators that may be used in the default
world!
17:12:33 [SEVERE] Plugin EssentialsChat vPre2.10.1.4 does not contain any generators that may be used in
the default world!
17:12:33 [SEVERE] Plugin Citizens v2.0.7-SNAPSHOT (build 685) does not contain any generators that may be
 used in the default world!
17:12:33 [SEVERE] Plugin WirelessRedstone v1.8.4b does not contain any generators that may be used in the
 default world!
17:12:33 [SEVERE] Plugin Vault v1.2.22-b277 does not contain any generators that may be used in the defau
lt world!
17:12:33 [SEVERE] Plugin GUI Creator v1.4.7 b1 does not contain any generators that may be used in the de
fault world!
17:12:33 [SEVERE] Plugin Denizen v0.7 does not contain any generators that may be used in the default wor
ld!
17:12:33 [SEVERE] Plugin Sentry v1.3.1 does not contain any generators that may be used in the default wo
rld!
17:12:33 [SEVERE] Plugin TreasureChest v8.3.9 does not contain any generators that may be used in the def
ault world!
17:12:33 [SEVERE] Plugin CraftBook v1795-7ca3b77 does not contain any generators that may be used in the
default world!
17:12:33 [SEVERE] Plugin ChestShop v3.46 does not contain any generators that may be used in the default
world!
17:12:33 [SEVERE] Plugin MobArena v0.94.4.95 does not contain any generators that may be used in the defa
ult world!
17:12:33 [SEVERE] Plugin MobHealth v5.3.4 does not contain any generators that may be used in the default
 world!
17:12:33 [SEVERE] Plugin UsefulPaper v0.2.1 does not contain any generators that may be used in the defau
lt world!
17:12:33 [SEVERE] Plugin CommandSigns v1.9.0.1 does not contain any generators that may be used in the de
fault world!
17:12:33 [SEVERE] Plugin FramePicture v1.3 does not contain any generators that may be used in the defaul
t world!
17:12:33 [SEVERE] Plugin PluginsBaker v0.3 does not contain any generators that may be used in the defaul
t world!
17:12:33 [SEVERE] Plugin iGates v0.6 does not contain any generators that may be used in the default worl
d!
17:12:33 [INFO] null
17:12:33 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvgens' in plugin Multiverse-
Core v2.4-b527
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
        at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
        at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerConnection.java:980)
        at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.java:898)
        at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:853)
        at org.getspout.spout.SpoutPlayerConnection.a(SpoutPlayerConnection.java:121)
        at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
        at org.getspout.spout.SpoutPlayerConnection.d(SpoutPlayerConnection.java:196)
        at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
        at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at me.duckdoom5.RpgEssentials.RpgEssentials.getDefaultWorldGenerator(RpgEssentials.java:296)
        at com.onarandombox.MultiverseCore.commands.GeneratorCommand.runCommand(GeneratorCommand.java:44)

        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.j
ava:279)
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler
.java:143)
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.
java:93)
        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 17 more
>
```

**Comment by TWSSYesterday** [comment]
This is no longer the case using the latest build(s).
