### ISSUE TITLE
Import world failure

### ISSUE THREAD

**Issue by craneboy2** [Multiverse/Multiverse-Core#1119]
Hello just tried to import a world and got this:

```
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:852)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:897)
12.03 08:58:29 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:979)
12.03 08:58:29 [Server] SEVERE at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:514)
12.03 08:58:29 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
12.03 08:58:29 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.03 08:58:29 [Server] SEVERE at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:877)
12.03 08:58:29 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
12.03 08:58:29 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
12.03 08:58:29 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
12.03 08:58:29 [Server] SEVERE at com.onarandombox.MultiverseCore.commands.RemoveCommand.runCommand(RemoveCommand.java:36)
12.03 08:58:29 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.removeWorldFromConfig(WorldManager.java:269)
12.03 08:58:29 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:746)
12.03 08:58:29 [Server] SEVERE java.lang.NullPointerException
12.03 08:58:29 [Server] INFO [Multiverse-Core] World 'newcrane' was removed from config.yml
12.03 08:58:29 [Server] INFO [Multiverse-Core] World 'newcrane' was unloaded from memory.
12.03 08:58:29 [Server] INFO Remember to Verify your email address when registering on our website
12.03 08:57:56 [Server] INFO 0 regions loaded for 'newcrane'
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:852)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:897)
12.03 08:57:47 [Server] SEVERE at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:979)
12.03 08:57:47 [Server] SEVERE at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:514)
12.03 08:57:47 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
12.03 08:57:47 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.03 08:57:47 [Server] SEVERE at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:877)
12.03 08:57:47 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
12.03 08:57:47 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
12.03 08:57:47 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
12.03 08:57:47 [Server] SEVERE at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
12.03 08:57:47 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:236)
12.03 08:57:47 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:746)
12.03 08:57:47 [Server] SEVERE java.lang.NullPointerException
12.03 08:57:47 [Server] INFO Loaded configuration for world 'newcrane'
12.03 08:57:47 [Server] INFO (newcrane) All fire spread is disabled.
12.03 08:57:47 [Server] INFO (newcrane) Lava fire is blocked.
12.03 08:57:47 [Server] INFO (newcrane) Lighters are PERMITTED.
12.03 08:57:47 [Server] INFO (newcrane) TNT ignition is PERMITTED.
12.03 08:57:46 [Server] INFO Preparing start region for level 4 (Seed: -5047062891834846325)
12.03 08:57:46 [Server] INFO [Multiverse-Core] Loading World & Settings - 'newcrane' - Env: NORMAL - Type: null
12.03 08:57:46 [Server] INFO craneboy2: Starting import of world 'newcrane'...
```

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest builds, ticket will be closed due to being ridiculously old.
