### ISSUE TITLE
Plugin Will Not Load

### ISSUE THREAD

**Issue by Rubberducky42** [Multiverse/Multiverse-Core#1303]
Multiverse-Core has been working fine for me, up until yesterday. I noticed I couldn't use any portals anymore. I looked in the console and I got this error log:

11:06:51 [SEVERE] Error occurred while enabling Multiverse-Core v2.5-b675 (Is it
 up to date?)
java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:64)
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManage
r.java:427)
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManage
r.java:402)
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManage
r.java:377)
        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldMa
nager.java:676)
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCor
e.java:303)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.jav
a:282)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.
java:264)
        at net.minecraft.server.v1_6_R2.MinecraftServer.l(MinecraftServer.java:3
13)
        at net.minecraft.server.v1_6_R2.MinecraftServer.f(MinecraftServer.java:2
90)
        at net.minecraft.server.v1_6_R2.MinecraftServer.a(MinecraftServer.java:2
50)
        at net.minecraft.server.v1_6_R2.DedicatedServer.init(DedicatedServer.jav
a:151)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java
:391)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:5
82)

**Comment by TWSSYesterday** [comment]
Definitely no longer the case, closing thread. That being said, it'd be nice to have some formatted replies instead of a spew of errors.
