### ISSUE TITLE
Can't import / create a world - An internal error occurred (...)

### ISSUE THREAD

**Issue by jyO2** [Multiverse/Multiverse-Core#131]
Hi all !

I just (re)created a craftbukkit server (1060), put 3 plugins : Essentials, PermissionsBukkit and Multiverse.

All is ok permissions are done, but when i'm trying to import or create a world, i get "An internal error occurred while attemping to perform this command".

Here is my log :

21:36:10 [INFO] Starting minecraft server version Beta 1.7.3
21:36:10 [INFO] Loading properties
21:36:10 [INFO] Starting Minecraft server on 77.111.245.18:25565
21:36:11 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-980-
g4ed23b1-b1060jnks (MC: 1.7.3)
21:36:11 [INFO] Preparing level "APu"
21:36:11 [INFO] Preparing start region for level 0 (Seed: 4302393903110997001)
21:36:11 [INFO] Preparing start region for level 1 (Seed: 4302393903110997001)
21:36:12 [INFO] Loaded Essentials build 2.5.8 by: Zenexer, ementalo, Aelux, Bret
tflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
21:36:12 [INFO] Essentials: Using config based permissions. Enable superperms in
config.
21:36:12 [INFO] MapMarkers version 0.3.2 enabled
21:36:12 [INFO] [Multiverse-Core] - Version 2.0-b265 Enabled - By Rigby and fern
ferret
21:36:12 [INFO] [AllPay] - Version 3.0 - hooked into Essentials Economy for Mult
iverse-Core v2.0-b265
21:36:12 [INFO] [Multiverse-Core] - Multiverse Config -- Loaded
21:36:12 [INFO] [Multiverse-Core] - World Config -- Loaded
21:36:12 [INFO] [Multiverse-Core] 0 - World(s) loaded.
21:36:12 [INFO] [MultiVerse-NetherPortals] - Version 2.0-b225 Enabled - By Rigby
and fernferret
21:36:12 [INFO] [MultiVerse-Portals] - Version 2.0-b254 Enabled - By Rigby and f
ernferret
21:36:12 [INFO] [MultiVerse-Portals] 0 - Portals(s) loaded
21:36:12 [INFO] PermissionsBukkit v1.2 is now enabled
21:36:12 [INFO] Essentials: Using PermissionsBukkit based permissions.
21:36:12 [INFO] Done (0.093s)! For help, type "help" or "?"
21:40:24 [INFO] jyO2 [/88.180.237.79:50717] logged in with entity id 114 at ([AP
u] -61.917869923669876, 70.0, -32.3041978215229)
21:40:28 [INFO] [PLAYER_COMMAND] jyO2: /time day
21:40:55 [INFO] Preparing start region for level 2 (Seed: -2705726335517218209)
21:40:56 [INFO] Preparing spawn area for testworld, 12%
21:40:57 [INFO] Preparing spawn area for testworld, 24%
21:40:58 [INFO] Preparing spawn area for testworld, 40%
21:40:59 [INFO] Preparing spawn area for testworld, 52%
21:41:00 [INFO] Preparing spawn area for testworld, 65%
21:41:01 [INFO] Preparing spawn area for testworld, 73%
21:41:02 [INFO] Preparing spawn area for testworld, 85%
21:41:03 [INFO] Preparing spawn area for testworld, 97%
21:41:04 [INFO] [Multiverse-Core] Loading World & Settings - 'testworld' - NORMA
L
**21:41:04 [SEVERE] null**
org.bukkit.command.CommandException: Unhandled exception executing command 'mv'
in plugin Multiverse-Core v2.0-b265
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:12
9)
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:3
52)
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:737)
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
**Caused by: java.lang.NoClassDefFoundError: org/bukkit/GameMode**
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:84)
at com.onarandombox.utils.WorldManager.addWorld(WorldManager.java:105)
at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(Cre
ateCommand.java:58)
at com.pneumaticraft.commandhandler.CommandHandler.checkAndRunCommand(Co
mmandHandler.java:245)
at com.pneumaticraft.commandhandler.CommandHandler.processFoundCommands(
CommandHandler.java:115)
at com.pneumaticraft.commandhandler.CommandHandler.locateAndRunCommand(C
ommandHandler.java:70)
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCo
re.java:410)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
... 12 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.GameMode
at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:36)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:24)
at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
... 20 more
21:41:10 [INFO] Connection reset
21:41:10 [INFO] jyO2 lost connection: disconnect.quitting

**Comment by Macintosh-Fan** [comment]
I have the same issue here now in 1.15.2.
