### ISSUE TITLE
Null world creation

### ISSUE THREAD

**Issue by Maxtroid** [Multiverse/Multiverse-Core#1403]
I have the TARDIS plugin created by eccentric_nz and I am trying to use Mutliverse-Core-2.4 to create a skylandsplus world to travel to. When I type the command "/mv create skylands normal -g SkylandsPlus", i get the chat message "An internal error occurred while attempting to perform this command". In the run.bat windows box the log shows:

[19:37:00] [Server thread/INFO]: KronBitz issued server command: /mv create skylands normal -g SkylandsPlus
[19:37:00] [Server thread/INFO]: KronBitz: Starting creation of world 'skylands'...[m
[19:37:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.4-b527
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:542) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:932) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:814) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R3/World
	at uk.co.jacekk.bukkit.skylandsplus.SkylandsPlus.getDefaultWorldGenerator(SkylandsPlus.java:32) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:289) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:182) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:113) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:94) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R3.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at uk.co.jacekk.bukkit.skylandsplus.SkylandsPlus.getDefaultWorldGenerator(SkylandsPlus.java:32) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:289) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:182) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:113) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:94) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	... 13 more
[19:38:31] [Server thread/INFO]: KronBitz issued server command: /mv create skylands normal -g SkylandsPlus
[19:38:31] [Server thread/INFO]: KronBitz: Starting creation of world 'skylands'...[m
[19:38:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.4-b527
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:542) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:932) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:814) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R3/World
	at uk.co.jacekk.bukkit.skylandsplus.SkylandsPlus.getDefaultWorldGenerator(SkylandsPlus.java:32) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:289) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:182) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:113) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:94) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R3.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at uk.co.jacekk.bukkit.skylandsplus.SkylandsPlus.getDefaultWorldGenerator(SkylandsPlus.java:32) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:289) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:182) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:113) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:94) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]

The plugins I have installed are:
HealthBar
LibsDisguises
Multiverse-Core-2.4
PermissionsBukkit-2.0
ProtocolLib-3.2.0
SkylandsPlus
Tardis
TardisChunkGenerator
TardisHorseSpeed
TardisWeepingAngels
Wereworlf
WorldBorder
WorldGuard

**Comment by TWSSYesterday** [comment]
Probably a generator issue, this is no longer the case after testing with other generators also and latest version. Locked due to inactivity and age of issue. If this happens again, please let us know!
