### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by DoctorWho10904** [Multiverse/Multiverse-Core#1522]
hello i have a error when i go in my ftp file and go to plugins then go to my multiverse-core file
theres no config nothing please help me

```
22.12 18:17:14 [Server] WARN at java.lang.Thread.run(Unknown Source)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:684)
22.12 18:17:14 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
22.12 18:17:14 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:918)
22.12 18:17:14 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1083)
22.12 18:17:14 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643)
22.12 18:17:14 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
22.12 18:17:14 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
22.12 18:17:14 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
22.12 18:17:14 [Server] WARN java.lang.NullPointerException
```

**Comment by TWSSYesterday** [comment]
Any updates on this?

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
