### ISSUE TITLE
Error ocurred while enabling Multiverse-Core

### ISSUE THREAD

**Issue by xtomyserrax** [Multiverse/Multiverse-Core#1527]
I am using: Spigot 1.7.10 - Multiverse-Core v2.5-b691  - Some of my worlds dont load

[18:31:43] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v2.5-b691 (Is it up to date?)
java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:64) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]

**Comment by TWSSYesterday** [comment]
Use latest Spigot version, and then pastebin the server's latest.log.

**Comment by xtomyserrax** [comment]
I am using 1.7.10 - I wont use 1.8 because i dont want it. Multiverse was working perfectly, i just created more worlds and now it doesnt work.

**Comment by TWSSYesterday** [comment]
Did you edit a setting in your worlds.yml?
