### ISSUE TITLE
"An Internal Error Occurred" When I try to /mvp create portals

### ISSUE THREAD

**Issue by mephils** [Multiverse/Multiverse-Core#1533]
Whenever I try to create portals I get this error, anyone know how to help?

[13:44:00] [Server thread/INFO]: mephils issued server command: /mvp create spawn2survival
[13:44:00] [Server thread/INFO]: WEAPI
[13:44:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-1543]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[minecraft_server.jar:git-Spigot-1543]
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:767) ~[minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:1015) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:845) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1543]
at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1543]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-1543]

**Comment by TWSSYesterday** [comment]
Using the 5.x branch of WorldEdit will fix this error.
