### ISSUE TITLE
World Creation Issue -|- Spigot 1.8.3

### ISSUE THREAD

**Issue by jccreszMinecraft** [Multiverse/Multiverse-Core#1567]
I have just gotten the latest available Bukkit version, 2.5.x, and I get this error:

[22:19:34] [Server thread/INFO]: jccreszMinecraft issued server command: /mvc Plots128 normal -g PlotMe-DefaultGenerator
[22:19:34] [Server thread/INFO]: jccreszMinecraft: Starting creation of world 'Plots128'...[m
[22:19:34] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'Plots128' - Env: NORMAL - Type: NORMAL & generator: PlotMe-DefaultGenerator
[22:19:34] [Server thread/INFO]: -------- World Settings For [Plots128] --------
[22:19:34] [Server thread/INFO]: View Distance: 14
[22:19:34] [Server thread/INFO]: Item Despawn Rate: 6000
[22:19:34] [Server thread/INFO]: Item Merge Radius: 2.5
[22:19:34] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:19:34] [Server thread/INFO]: Arrow Despawn Rate: 1200
[22:19:34] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[22:19:34] [Server thread/INFO]: Chunks to Grow per Tick: 650
[22:19:34] [Server thread/INFO]: Clear tick list: false
[22:19:34] [Server thread/INFO]: Experience Merge Radius: 3.0
[22:19:34] [Server thread/INFO]: Anti X-Ray: true
[22:19:34] [Server thread/INFO]: 	Engine Mode: 1
[22:19:34] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[22:19:34] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[22:19:34] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[22:19:34] [Server thread/INFO]: Max Entity Collisions: 8
[22:19:34] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[22:19:34] [Server thread/INFO]: Mob Spawn Range: 4
[22:19:34] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[22:19:34] [Server thread/INFO]: Cactus Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Cane Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Melon Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Sapling Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Wheat Growth Modifier: 100%
[22:19:34] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[22:19:34] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:19:34] [Server thread/INFO]: Random Lighting Updates: false
[22:19:34] [Server thread/INFO]: Structure Info Saving: true
[22:19:34] [Server thread/INFO]: Sending up to 5 chunks per packet
[22:19:34] [Server thread/INFO]: Max TNT Explosions: 100
[22:19:34] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:19:34] [Server thread/INFO]: GroupManager - INFO - New world detected...
[22:19:34] [Server thread/INFO]: GroupManager - INFO - Creating data for: Plots128
[22:19:34] [Server thread/INFO]: GroupManager - INFO - Don't forget to configure/mirror this world in config.yml.
[22:19:34] [Server thread/INFO]: Preparing start region for level 3 (Seed: 4548802036143902136)
[22:19:34] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\Jacob\MediaFire\Ice Network Final\Creative Server\plugins\WorldGuard\worlds\Plots128\config.yml
[22:19:34] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\Jacob\MediaFire\Ice Network Final\Creative Server\plugins\WorldGuard\worlds\Plots128\blacklist.txt
[22:19:34] [Server thread/INFO]: [WorldGuard] (Plots128) TNT ignition is PERMITTED.
[22:19:34] [Server thread/INFO]: [WorldGuard] (Plots128) Lighters are PERMITTED.
[22:19:34] [Server thread/INFO]: [WorldGuard] (Plots128) Lava fire is blocked.
[22:19:34] [Server thread/INFO]: [WorldGuard] (Plots128) Fire spread is UNRESTRICTED.
[22:19:34] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'Plots128'
[22:19:34] [Server thread/ERROR]: Could not pass event WorldLoadEvent to Multiverse-Core v2.5-b691
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:938) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:463) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897) [Multiverse-Core-2.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1138) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:973) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getChunkAt(CraftWorld.java:125) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:89) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:567) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	... 29 more
Caused by: java.lang.NullPointerException
	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:142) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getChunkAt(CraftWorld.java:125) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:89) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:567) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	... 29 more
[22:19:34] [Server thread/WARN]: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getChunkAt(CraftWorld.java:125)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:89)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:567)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[22:19:34] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[22:19:34] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[22:19:34] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[22:19:34] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1138)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:973)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[22:19:34] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:19:34] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[22:19:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:19:34] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[22:19:34] [Server thread/WARN]: 	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47)
[22:19:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53)
[22:19:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:142)
[22:19:34] [Server thread/WARN]: 	... 32 more

I hope I can get assistance on this.

**Comment by ryantheleach** [comment]
Caused by: java.lang.NullPointerException
at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47) ~[?:?]

Would suggest it's likely plotme at fault, but doesn't rule out Multiverse completely.

**Comment by TWSSYesterday** [comment]
@ryantheleach It's a PlotMe issue :), tested a few of their builds and most of them spew out this error but a few prior to a large update don't.

**Comment by jccreszMinecraft** [comment]
Do you guys have any direct contacts?

**Comment by TWSSYesterday** [comment]
thetryhardnoob@gmail.com is my email

**Comment by jccreszMinecraft** [comment]
:3 derp. I forgot you were a developer on this.
