### ISSUE TITLE
Creating Netherportal im Nether with Error

### ISSUE THREAD

**Issue by Telbaru** [Multiverse/Multiverse-Core#1589]
I allow the option to create netherportals in my mainworld (kieselkiste). The portal function perfectly and all okay. Now i want to create a portal in Kieselkiste_nether and i have set the option for this world "portalForm: NONE". I can create a portal without problems and can use it and this error comes:

I uses Spigot: Version git-Spigot-f928e7a-e91aed8 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT) with Multiverse-Core v2.5-b692 and Multiverse-Portals v2.5-bUNKNOWN.

[22:12:24 ERROR]: Could not pass event PortalCreateEvent to Multiverse-Core v2.5
-b692
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.BlockPortal$Shape.e(BlockPortal.java:346
) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.BlockPortal.e(BlockPortal.java:81) [spig
ot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.BlockFire.onPlace(BlockFire.java:335) [s
pigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:183)
[spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInt
eractManager.java:503) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:736) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:52) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:1) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spig
ot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
18) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
67) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
57) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:560) [spigot.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.listeners.MVPortalListener.portalForm
(MVPortalListener.java:58) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
        ... 20 more

**Comment by TWSSYesterday** [comment]
Need pastebin'ed log file and other versions.

**Comment by Telbaru** [comment]
http://pastebin.com/EJUiT2ZD

**Comment by Telbaru** [comment]
and maybe it is possible, i'm using java 1.8.0_31

**Comment by TWSSYesterday** [comment]
That's not the entire log

**Comment by Telbaru** [comment]
thats the complete file what i have, if the server is running. Do you want the rest when the server is stopping? here it is...the console cut the error and shows ...20 more...no idea how i can show the complet error
http://pastebin.com/f4bCJf7Q

maybe  globaldebug: '0-3' in the multiverse config?

**Comment by dumptruckman** [comment]
I believe you're somehow portaling in a world not managed by Multiverse. I just pushed something that should prevent this error and not attempt to handle worlds not managed by Multiverse.
