### ISSUE TITLE
2 bug's in Multiverse-Core v2.5-b710

### ISSUE THREAD

**Issue by CrispyBoBo** [Multiverse/Multiverse-Core#1634]
So, i wanted to create a largebiomes world and i got an error. While looking the logs i found anohter one while loading the plugin. 
While starting up:
 [14:28:36] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b710
[14:28:36] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v2.5-b710 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Difficulty.PEACEFULL
	at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.7.0_79]
	at org.bukkit.Difficulty.valueOf(Difficulty.java:1) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at com.onarandombox.MultiverseCore.MultiverseCore.migrateWorldConfig(MultiverseCore.java:752) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:494) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:305) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

While creating the world:
[14:29:16] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 8%
[14:29:17] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 20%
[14:29:19] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 40%
[14:29:20] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 56%
[14:29:21] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 77%
[14:29:22] [Server thread/INFO]: Preparing spawn area for RiseOfKingdoms, 93%
[14:29:22] [Server thread/WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[14:29:22] [Server thread/WARN]: [Multiverse-Core] Original Location: X: 0 Y: 0 Z: 0 P: 0 Y: 0 
[14:29:22] [Server thread/INFO]: [Multiverse-Core] New Spawn for 'RiseOfKingdoms' is located at: RiseOfKingdoms:0.00,127.00,0.00:0.00:0.00
[14:29:22] [Server thread/WARN]: java.lang.NullPointerException
[14:29:22] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:806)
[14:29:22] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:273)
[14:29:22] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[14:29:22] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[14:29:22] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[14:29:22] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[14:29:22] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:898)
[14:29:22] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:29:22] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:29:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[14:29:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:626)
[14:29:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[14:29:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[14:29:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[14:29:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[14:29:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:29:22] [Server thread/INFO]: An internal error occurred when attempting to perform this command.
[14:29:22] [Server thread/INFO]: Details were printed to the server console and logs, please add that to your bug report.

**Comment by CrispyBoBo** [comment]
Version: Spigot 1.8.7
Plugins:

AutoBroadcast 1.4.6.jar
Citizens.jar
CleanroomGenerator.jar
Clearlag.jar
Essentials-2.x-SNAPSHOT.jar
EssentialsChat-2.x-SNAPSHOT.jar
EssentialsProtect-2.x-SNAPSHOT (1).jar
EssentialsSpawn-2.x-SNAPSHOT.jar
GetStaff.jar
GiantTrees-1.1.jar
HolographicDisplays.jar
InfoBoardReborn_v1.7.0.jar
Multiverse-Core-2.5 (1).jar
PermissionsEx-1.23.3.jar
ServerSigns.jar
Vault.jar
VillagerShop.jar
VoxelSniper-5.170.0-SNAPSHOT.jar
worldedit-bukkit-6.1.jar

**Comment by CrispyBoBo** [comment]
Same for Multiverse-Core v2.5-b691.

**Comment by dumptruckman** [comment]
It would appear that you attempted to upgrade from Core 2.3 or 2.4 (can't remember which) but must have manually edited your world file and changed the difficulty to "peacefull" rather than "peaceful". The spelling here was critical so I'm going to implement a fix to protect against bad spelling crashing the migration process.

The second error likely occurred because the first one left the plugin in a faulty state. It's possible if you rerun it will fix it. And if not, you can simply fix the spelling mistake and that should fix the issue.

**Comment by dumptruckman** [comment]
I just pushed a change that should forever prevent this error in the future.

**Comment by CrispyBoBo** [comment]
Okay so it didnt crash with 2.4-AB, but couldnt create largebiome ofc. I'm now going to fix the spelling problem and post the results.

**Comment by CrispyBoBo** [comment]
Thanks! Worked fine! And i got a last question. Do you now a generator plugin that it is possible to make a world with awesome trees and landscape?

**Comment by dumptruckman** [comment]
No, sorry.

**Comment by CrispyBoBo** [comment]
Np ;) Thanks anyways.
