### ISSUE TITLE
PLEASE HELPE ME!! :(

### ISSUE THREAD

**Issue by EduBar01** [Multiverse/Multiverse-Core#1639]
When i import/load 1 world the plugin crash!!!

28.12 14:36:19 [Server] WARN at java.lang.Thread.run(Unknown Source)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
28.12 14:36:19 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
28.12 14:36:19 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966)
28.12 14:36:19 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106)
28.12 14:36:19 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620)
28.12 14:36:19 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
28.12 14:36:19 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:898)
28.12 14:36:19 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
28.12 14:36:19 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
28.12 14:36:19 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
28.12 14:36:19 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:64)
28.12 14:36:19 [Server] WARN java.lang.NullPointerException
28.12 14:36:19 [Server] INFO World world_LobbySurvivalGames is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from world_LobbySurvivalGames's world directory if you want to be able to load the duplicate world.

**Comment by EduBar01** [comment]
28.12 14:36:19 [Server] INFO World world_LobbySurvivalGames is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from world_LobbySurvivalGames's world directory if you want to be able to load the duplicate world.
Is this?

**Comment by EduBar01** [comment]
OMG Finely!!!! :dancers:

**Comment by EduBar01** [comment]
im soooo stupid
