### ISSUE TITLE
Player teleport error?

### ISSUE THREAD

**Issue by Jadeng47** [Multiverse/Multiverse-Core#1647]
This Error Keeps appearing on My console: I've already sent this error on the Citizens 2 page...

```
12:14:25 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
 org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385) [Citizens.jar:?]
 at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:411) [Citizens.jar:?]
 at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1022) [sentry.jar:?]
 at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128) [sentry.jar:?]
 at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:235) [Citizens.jar:?]
 at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128) [Citizens.jar:?]
 at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179) [Citizens.jar:?]
 at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32) [Citizens.jar:?]
 at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222) [Citizens.jar:?]
 at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118) [Citizens.jar:?]
 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Bukkit-18fbb24]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
 Caused by: java.lang.NullPointerException
 at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 ... 22 more
 [12:14:25 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
 org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [minecraft_server.jar:git-Bukkit-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385) [Citizens.jar:?]
 at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:411) [Citizens.jar:?]
 at net.citizensnpcs.api.ai.TeleportStuckAction.run(TeleportStuckAction.java:40) [Citizens.jar:?]
 at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:234) [Citizens.jar:?]
 at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:139) [Citizens.jar:?]
 at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) [Citizens.jar:?]
 at net.citizensnpcs.npc.entity.EntityHumanNPC.t_(EntityHumanNPC.java:339) [Citizens.jar:?]
 at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1420) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.World.g(World.java:1398) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1269) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:560) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:727) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [minecraft_server.jar:git-Bukkit-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Bukkit-18fbb24]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
 Caused by: java.lang.NullPointerException
 at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-Bukkit-18fbb24]
 ... 21 more

Caused By:
java.lang.NullPointerException at
 com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
```

Thank You For Reading

**Comment by TWSSYesterday** [comment]
Update Multiverse, then send new error log in pastebin if it continues :)

**Comment by Jadeng47** [comment]
This Error or warn might be the case:
[11:56:18 WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[11:56:18 WARN]: [Multiverse-Core] Original Location: X: -202 Y: 64 Z: 361 P: 0 Y: 0 
[11:56:18 ERROR]: [Multiverse-Core] New safe spawn NOT found!!!
[11:56:18 INFO]: [Multiverse-Core] Loading World & Settings - 'My World 2_the_end' - Env: THE_END - Type: NORMAL & seed: -6673127877177967286
[11:56:18 INFO]: [Multiverse-Core] Loading World & Settings - 'My World 2' - Env: NORMAL - Type: NORMAL & seed: 0
[11:56:18 INFO]: Preparing start region for level 3 (Seed: 0)
[11:56:19 INFO]: Preparing spawn area for My World 2, 44%
[11:56:20 INFO]: [Multiverse-Core] 1 - World(s) loaded.
[11:56:20 WARN]: [Multiverse-Core] The world specified as the spawn world (My World 2) did not exist!!

**Comment by TWSSYesterday** [comment]
Your world has spaces in :)

**Comment by Jadeng47** [comment]
so should I change the world's name?

**Comment by dumptruckman** [comment]
Spaces in the name should be fine. But I need to know what version of MV you're using in order to figure out what is actually going wrong. Best bet would be to first update to the latest dev build on http://ci.onarandombox.com and see if you can reproduce the error with that. If so, send updated error logs.

**Comment by FernFerret** [comment]
Spaces should be fine, but do read our note about spaces in world names: https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#a-note-about-spaces-in-world-names

**Comment by FernFerret** [comment]
Also, actually, this is an ancient version: 

```
Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
```

Hi there, please make sure you've updated your Multiverse-Core version via our [Jenkins Page](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/). If the issue persists, please post some additional logs. You should be on **b716**+ (at the time of this comment).

**Comment by FernFerret** [comment]
Closing due to lack of response (sorry). If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post additional details here and we'll reopen it! Thanks!
