### ISSUE TITLE
World keeps unloading

### ISSUE THREAD

**Issue by cj89898** [Multiverse/Multiverse-Core#1649]
My world keeps unloading. World not loading is: 'end'

Here are some important files:

worlds.yml: http://pastebin.com/1gBp3fc0
Startup log: http://justpaste.it/qnlj
Multiverse Version Output: http://pastebin.com/4mKgYtyt

**Comment by waterlubber** [comment]
I can confirm this issue, at server load up only our main world ("world") is loaded, we have ~17 others that do not load, but CAN be loaded manually with /mv load. Obviously not loading on startup breaks quite a few things (Claimblocks removes claims there, portals break) and we're having quite an issue.

Here's my relevant log:

```
java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:64) ~[?:?]
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-18fbb24]
```

**Comment by cj89898** [comment]
Mine unloads every single time I load it. Not sure why...

**Comment by cj89898** [comment]
Bump

**Comment by TWSSYesterday** [comment]
Don't feel you have to bump this, the team are often busy with other projects or perhaps working on getting a fix for it.

**Comment by cj89898** [comment]
Sounds good, not my biggest issue at this point. Some other plugin is spamming my console lol.

**Comment by waterlubber** [comment]
The issue seems to like, for myself at least, in worlds not loading at start, and unloading randomly from then on.

**Comment by dumptruckman** [comment]
If you load a world and it immediately unloads then something is probably wrong with the world. Multiverse has no control over the server deciding it doesn't like a world and unloading it. As for randomly being unloaded, this is likely the same issue. Multiverse does not have anything in it's code that tells the server to randomly unload worlds. They will only be unloaded by Multiverse when you ask them to be, literally no other time.

Unfortunately our support for mod servers is pretty limited as setting up a test environment is complicated but more importantly very hard to match to the end user. I would recommend seeking help from the developers of your server software or the makers of the worlds that are not loading. We have tried to at least make Multiverse work at all with modded servers but we can't do much more beyond that.

Good luck!

**Comment by dumptruckman** [comment]
@waterlubber I would recommend at least updating to the latest dev build from http://ci.onarandombox.com as your stacktrace doesn't point to any valid code in the latest source, which makes it very hard to determine what is going on. The cause of the error is that somehow a null world is being passed into MVWorld but WHY that is is hard to say.

**Comment by waterlubber** [comment]
Yep, your fix did it. Thanks.

For future reference, we were able to manually load with /mv load and ended up setting up a script to auto-load every time the server restarted. Now, we don't need it, hooray!

**Comment by dumptruckman** [comment]
Well. I guess I understand why world's would not autoload for some people. Because some servers would return a null world and MV would error before it finished loading the other worlds. I think this might be the fix for the long standing known issue!

**Comment by cj89898** [comment]
So do you recommend the same thing for me? to update to latest dev build?

**Comment by waterlubber** [comment]
Worked fine, no harm in doing it.

**Comment by cj89898** [comment]
Interesting, still doesn't work. I am running KCauldron though. But I have a server for pack SF2 and a server for Project Ozone and the one on Project Ozone works fine.

**Comment by i9hdkill** [comment]
Kcauldron is pretty much broken. Getting these issues on my test enviroment too with mv-core, Use Cauldron, It's old but working. Something around Cauldron forge 1236 Build 210 (if your mod packs are fine this low forge version)
At least it's working for me.

**Comment by cj89898** [comment]
How exactly do I set a startupflag? Do you mean in the batch file?

**Comment by i9hdkill** [comment]
yes, It's a java flag

**Comment by cj89898** [comment]
So how would I write it?

`java -Xms512m -Xmx4096m -jar KCauldron.jar nogui -Dfile.encoding=UTF-8`

**Comment by i9hdkill** [comment]
like this:
java -Xms512m -Xmx4096m -Dfile.encoding=UTF-8 -jar KCauldron.jar nogui
The flag ensures that config files are loaded as utf8.
after adding the flag check all your config files for yml errors with a yml validator and save them as utf8.
you can add me on skype if you need further help to prevent email spam for the other participants watching this ticket.
jonnni239
