### ISSUE TITLE
Import Error and after restart worlds delete from config

### ISSUE THREAD

**Issue by GolexoS** [Multiverse/Multiverse-Core#1691]
Hey,

1. when i restart the Server, the worlds is delete from the Multiverse.....

2. when i import a map become i that issues:

```
[23:10:52] [Server thread/WARN]: java.lang.NullPointerException
[23:10:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:770)
[23:10:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:237)
[23:10:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
[23:10:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[23:10:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[23:10:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[23:10:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[23:10:52] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:10:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:10:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:10:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[23:10:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[23:10:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[23:10:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:10:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:10:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:10:52] [Server thread/INFO]: An internal error occurred when attempting to perform this command.
[23:10:52] [Server thread/INFO]: Details were printed to the server console and logs, please add that to your bug report.
```

Multiverse-Core: 2.5 b699

Spigot 1.8.8

**Comment by dumptruckman** [comment]
I'm not entirely sure what is going wrong here... This error just simply shouldn't happen. My best guess is your jar file is corrupted. Try redownloading the plugin jar.

**Comment by GolexoS** [comment]
I updated the Multiverse Plugin, now i make an restart to See the result

**Comment by GolexoS** [comment]
OK, all map are delete Form the config.....

**Comment by GolexoS** [comment]
OK .........

**Comment by GolexoS** [comment]
Its THe same issues

**Comment by FernFerret** [comment]
This issue either does not have enough details, or details have been requested and not provided. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report.

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.
