### ISSUE TITLE
Error on clean Startup

### ISSUE THREAD

**Issue by Saithgame** [Multiverse/Multiverse-Core#1702]
Hey, ive got some Errors with the newest MV-Core Build (2.5 Multiverse Beta Build #68)
Im running the latest spigot/bukkit build 1.9.2
This is the log it creates :

[14:42:53 WARN]: Exception in thread "pool-3-thread-1"
[14:42:53 WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b688 generated an exception while executing task 3
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

ive set up a new server with a new world and no plugins but i always get this error, is there something i can do against it?

**Comment by dumptruckman** [comment]
You need to use dev builds for 1.9. They are available here: http://ci.onarandombox.com/view/Multiverse/
