### ISSUE TITLE
World cant be loaded

### ISSUE THREAD

**Issue by KeksKartoffe** [Multiverse/Multiverse-Core#1708]
If i start my start or if i write /mvim Lobby normal than its belongs an error:

``````
[13:11:27 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[13:11:27 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[13:11:27 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[13:11:27 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[13:11:27 INFO]: [WorldGuard] Loading region data...
[13:11:27 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b719
[13:11:27 WARN]: [Multiverse-Core] Exception while loading value for environment
[13:11:27 WARN]: [Multiverse-Core] Exception while loading value for environment
[13:11:28 WARN]: java.lang.NullPointerException
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.WorldServer.<init>(WorldServer.java:53)
[13:11:28 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:8
92)
[13:11:28 WARN]: at org.bukkit.Bukkit.createWorld(Bukkit.java:468)
[13:11:28 WARN]: at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[13:11:28 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.ja
va:466)
[13:11:28 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.ja
va:447)
[13:11:28 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.ja
va:422)
[13:11:28 WARN]: at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManage
r.java:725)
[13:11:28 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.ja
va:309)
[13:11:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:11:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.jav
a:340)
[13:11:28 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.ja
va:405)
[13:11:28 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:36
1)
[13:11:28 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java
:321)
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:26
9)
[13:11:28 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527
)
[13:11:28 WARN]: at java.lang.Thread.run(Thread.java:745)
[13:11:28 ERROR]: [Multiverse-Core] The world 'Lobby' could NOT be loaded because it contains errors
and is probably corrupt!
[13:11:28 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Lobby'
[13:11:28 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[13:11:28 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[13:11:28 INFO]: [Multiverse-Core] Version 2.5-b719 (API v20) Enabled - By Rigby, fernferret, lithiu```
``````

**Comment by KeksKartoffe** [comment]
@FernFerret

**Comment by electronicboy** [comment]
Have you checked that there actually isn't an issue with the map? e.g. what happens if you create a server with just that map at the side?

**Comment by KeksKartoffe** [comment]
I can load the Map in Single Player and on my other Server, where i have created it. 

A normal Map can be created without a problem

**Comment by electronicboy** [comment]
If normal maps can be created and loaded without any issues it more points to a map problem then. Did you test the actual copy of the map that you've got on that server? e.g. did you redownload/copy it from the server with the error and test that?

I'd consider backing up your worlds.yml file and either removing the lobby world or just resetting the full config file and attempting to import any worlds you have on there from scratch

**Comment by KeksKartoffe** [comment]
I have copy and paste it with an schematic^^

**Comment by electronicboy** [comment]
What do you mean by that? How does that change the fact that there is the potential that there is an issue with either your worlds file or the world itself?

**Comment by KeksKartoffe** [comment]
I have created an emty World with Multiverse and i have pasted an schematic of the Lobby...

**Comment by electronicboy** [comment]
Quick skim of the code involved points either to your worlds.yml being screwed, or your level.dat being screwed;
Unless you test an exact copy of that world folder which is throwing the errors, or you try to clear the issue which could potentially be in worlds.yml (which I doubt) you can't rule out either of them being the cause.

**Comment by FernFerret** [comment]
@electronicboy is correct. Please test the exact world. Making a copy won't do because metadata might get recreated. If you're able to load a copy, why not remove the bad world and move the working copy in place?
