### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by aaron1998ish** [Multiverse/Multiverse-Core#1712]
Hi, im using your 1.9 version of Multiverse-core, on the latest spigot and im getting this error:

My Spigot version is:
[03:02:23 INFO]: This server is running CraftBukkit version git-Spigot-e6f93f4-e
d60c01 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

[02:51:19 WARN]: Exception in thread "Craft Scheduler Thread - 166"
[02:51:19 WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-C
ore v2.5-b710 generated an exception while executing task 1837
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

**Comment by FernFerret** [comment]
This issue either does not have enough details, or details have been requested and not provided. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report.

**Comment by aaron1998ish** [comment]
Honestly "Not enough information" , reading the stack trace should be more than enough to say that "metrics" is broken.
"NoSuchMethodError" and:
at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)

I took a look at the metrics in your current build...
Try changing:
int playersOnline = Bukkit.getServer().getOnlinePlayers().length; 
to 
int playersOnline = Bukkit.getServer().getOnlinePlayers().size();

Im sure you guys know what you're doing and get rather busy when it comes to reading these reports, but if you actually read that stack trace and still believed that it wasnt enough information.... then lmao

**Comment by dumptruckman** [comment]
I would recommend using the 1.9 builds of the plugin instead of old stuff. That helps too. http://ci.onarandombox.com/job/Multiverse-Core/
I'm not sure where you're getting the idea that the build you're using is for 1.9 cause it isn't. We fixed that bug already the day 1.9 came out.

**Comment by FernFerret** [comment]
@aaron1998ish we're in the process (@dumptruckman has mentioned it in other tickets) of updating our systems and versions to provide a cleaner access point to our code. Please make sure you're getting our source ONLY from the following places:

* http://ci.onarandombox.com (we should get @Rigby90 to use Let's Encrypt and HTTPS this guy)
* dev.bukkit.org

PS: The reason I'd asked for more info was so I could get a version number. We have nothing against any individual user, but providing all of the details in the "submitting a bug" section helps us identify problems quicker.

@dumptruckman: I'll get the github Issue template committed this weekend.

**Comment by dumptruckman** [comment]
@FernFerret Just pointing out that the stack trace does actually show a version number "Plugin Multiverse-Core v2.5-b710 generated an exception". What is an issue template?

**Comment by FernFerret** [comment]
@dumptruckman heh, I didn't notice because the code wasn't properly markdown'd (which our `mvv` would do). That's me being guilty of skimming, also all of the details in our "Writing a bug" page are never hurtful in debugging a problem :smile: 

Issue templates let us provide a default checklist for issues (and/or pull requests). See [here](https://github.com/blog/2111-issue-and-pull-request-templates) to read about issue templates.
