### ISSUE TITLE
Load plugin ERROR !

### ISSUE THREAD

**Issue by zR3bo0t** [Multiverse/Multiverse-Core#1713]
[18:30:49 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:30:49 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:30:49 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[18:30:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[18:30:49 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[18:30:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[18:30:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[18:30:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292)
[18:30:49 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[18:30:49 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)

**Comment by FernFerret** [comment]
This issue either does not have enough details, or details have been requested and not provided. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report.

It's likely that your plugin is out of date.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
