### ISSUE TITLE
exception when both use hotpotato and Multivese-Core

### ISSUE THREAD

**Issue by alex450** [Multiverse/Multiverse-Core#1715]
When i issue the command , it happened
hotpotato 's link : http://dev.bukkit.org/bukkit-plugins/hot-potato/

```
[03:19:17 INFO]: Alexander_Inf issued server command: /hp
[03:19:21 INFO]: Alexander_Inf issued server command: /hp join minihp
[03:19:21 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.5.0-SNAPSHOT-b722
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:533) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.teleport(CraftEntity.java:231) [patched.jar:git-TacoSpigot-"38b63d6"]
        at me.avery246813579.hotpotato.game.GameManager.joinGame(GameManager.java:211) [potato.jar:?]
        at me.avery246813579.hotpotato.commands.JoinCommand.runCommand(JoinCommand.java:33) [potato.jar:?]
        at me.avery246813579.hotpotato.commands.GameClass.run(GameClass.java:54) [potato.jar:?]
        at me.avery246813579.hotpotato.commands.GameCommand.onCommand(GameCommand.java:36) [potato.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:178) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        ... 26 more
[03:19:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hp' in plugin HotPotato v1.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at me.avery246813579.hotpotato.commands.GameCommand.onCommand(GameCommand.java:36) [potato.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at me.avery246813579.hotpotato.commands.GameCommand.onCommand(GameCommand.java:36) [potato.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at me.avery246813579.hotpotato.commands.GameCommand.onCommand(GameCommand.java:36) [potato.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:178) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        ... 26 more
[03:19:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hp' in plugin HotPotato v1.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched.jar:git-TacoSpigot-"38b63d6"]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched.jar:git-TacoSpigot-"38b63d6"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:549) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.teleport(CraftEntity.java:231) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        at me.avery246813579.hotpotato.game.GameManager.joinGame(GameManager.java:211) ~[?:?]
        at me.avery246813579.hotpotato.commands.JoinCommand.runCommand(JoinCommand.java:33) ~[?:?]
        at me.avery246813579.hotpotato.commands.GameClass.run(GameClass.java:54) ~[?:?]
        at me.avery246813579.hotpotato.commands.GameCommand.onCommand(GameCommand.java:36) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"38b63d6"]
        ... 15 more
```

**Comment by FernFerret** [comment]
The line that's erroring (it seems) is [this one](https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/listeners/MVPlayerListener.java#L178). Now, I can't tell from the traceback exactly which part is undefined, the world name (unlikely), the world (likely), or the location (also likely). but something is amiss here. I don't have time to fire up a new server with this plugin (since it's most likely causing it) but I could give you a custom build that has more debug if you'd like.
