### ISSUE TITLE
Error with SG worlds

### ISSUE THREAD

**Issue by GothkittyGirl** [Multiverse/Multiverse-Core#1749]
12.08 13:51:04 [Server] ERROR Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
12.08 13:51:04 [Server] INFO org.bukkit.event.EventException
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:459) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.teleport(CraftEntity.java:226) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at me.wazup.survivalgames.main.onCommand(main.java:321) [SurvivalGames.jar:?]
12.08 13:51:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at me.wazup.survivalgames.listener.onInteraction(listener.java:264) [SurvivalGames.jar:?]
12.08 13:51:04 [Server] INFO at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source) ~[?:?]
12.08 13:51:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
12.08 13:51:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
12.08 13:51:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
12.08 13:51:04 [Server] INFO Caused by: java.lang.NullPointerException
12.08 13:51:04 [Server] INFO at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:222) ~[?:?]
12.08 13:51:04 [Server] INFO at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source) ~[?:?]
12.08 13:51:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
12.08 13:51:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
12.08 13:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-latest.jar:git-Spigot-10d38f1-5e5cf84]
12.08 13:51:04 [Server] INFO ... 32 more

**Comment by GothkittyGirl** [comment]
ok looks like to be the world itself, not the SG sign doing it.

**Comment by GothkittyGirl** [comment]
Disreguard i was able to join the world even tho i hadnt loaded it with multiverse. I loaded it with multiverse and no more errors.
