### ISSUE TITLE
MV can't laod World - Error

### ISSUE THREAD

**Issue by Ishidres** [Multiverse/Multiverse-Core#1774]
MV tries to load a world, but it doesn't work. It doesn't even get the name of the world. It just says:
```
[14:39:12] [Server thread/ERROR]: [Multiverse-Core] The world '{NAME}' could NOT be loaded because it contains errors and is probably corrupt!
[14:39:12] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! '{NAME}'
[14:39:12] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
```
Before it says this, it gives me an Error:

```
[14:39:12] [Server thread/WARN]: java.lang.NullPointerException
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.<init>(WorldServer.java:58)
[14:39:12] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:887)
[14:39:12] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[14:39:12] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[14:39:12] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[14:39:12] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
[14:39:12] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
[14:39:12] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676)
[14:39:12] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[14:39:12] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:39:12] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:39:12] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:39:12] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[14:39:12] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[14:39:12] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[14:39:12] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
```

I can't read anything out of this Error log, please help me!

You can find the whole error log by Multiverse also here:
http://pastebin.com/mYB75BLv

Hope you can help me!
Best wishes, Ishidres

**Comment by Ishidres** [comment]
**It would alread be enough to just know the name of the world.
Can anyone please help me??

I can't start my server any more because of this problem!!**

**Comment by TWSSYesterday** [comment]
`[14:39:12] [Server thread/ERROR]: [Multiverse-Core] The world '{NAME}' could NOT be loaded because it contains errors and is probably corrupt!
[14:39:12] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! '{NAME}'
[14:39:12] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer`
Use this tool, update Multiverse and server jar and if that doesn't work come back with full latest.log
