### ISSUE TITLE
Error multiverse import

### ISSUE THREAD

**Issue by opped** [Multiverse/Multiverse-Core#1784]
I want to import the lobby world.. but when i start the console first, it spawn me this error:
`[00:05:10 WARN]: java.io.FileNotFoundException: ./lobby/session.lock (Permission denied)>
[00:05:10 WARN]: 	at java.io.FileOutputStream.open0(Native Method)>
[00:05:10 WARN]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)>
[00:05:10 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)>
[00:05:10 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.WorldNBTStorage.i(WorldNBTStorage.java:53)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.WorldNBTStorage.<init>(WorldNBTStorage.java:47)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.ServerNBTManager.<init>(SourceFile:21)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.createWorld(CraftServer.java:886)>
[00:05:10 WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:468)>
[00:05:10 WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)>
[00:05:10 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)>
[00:05:10 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)>
[00:05:10 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)>
[00:05:10 WARN]: 	at java.lang.Thread.run(Thread.java:745)>
[00:05:10 WARN]: java.lang.RuntimeException: Failed to check session lock for world located at ./lobby, aborting. Stop the server and delete the session.lock in this world to prevent further issues.>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.WorldNBTStorage.i(WorldNBTStorage.java:63)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.WorldNBTStorage.<init>(WorldNBTStorage.java:47)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.ServerNBTManager.<init>(SourceFile:21)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.createWorld(CraftServer.java:886)>
[00:05:10 WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:468)>
[00:05:10 WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)>
[00:05:10 WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)>
[00:05:10 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)>
[00:05:10 WA
RN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)>
[00:05:10 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)>
[00:05:10 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)>
[00:05:10 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)>
[00:05:10 WARN]: 	at java.lang.Thread.run(Thread.java:745)>
[00:05:10 ERROR]: [Multiverse-Core] The world 'lobby' could NOT be loaded because it contains errors and is probably corrupt!>
[00:05:10 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'lobby'>
[00:05:10 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer>`
Please Help me, i'm going crazy! (I've already deleted session.lock file in lobby folder but nothing..)

**Comment by opped** [comment]
Solved, you must access to sftp with credentials situated in your server Pufferpanel.

**Comment by opped** [comment]
Not as a root. Bye!
