### ISSUE TITLE
1.12 compatibility

### ISSUE THREAD

**Issue by RedLight66** [Multiverse/Multiverse-Core#1813]
Hello !

I'm in test period with Spigot-1.12.pre2 and your plugin isn't compatible.
Could you update it ? :p

There is the issue:
`[15:00:44] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b717
[15:00:44] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v2.5-b717 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
    at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:483) ~[?:?]
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:305) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom.jar:git-Spigot-1ffab67-45102fc]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [custom.jar:git-Spigot-1ffab67-45102fc]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [custom.jar:git-Spigot-1ffab67-45102fc]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [custom.jar:git-Spigot-1ffab67-45102fc]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [custom.jar:git-Spigot-1ffab67-45102fc]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [custom.jar:git-Spigot-1ffab67-45102fc]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [custom.jar:git-Spigot-1ffab67-45102fc]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [custom.jar:git-Spigot-1ffab67-45102fc]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [custom.jar:git-Spigot-1ffab67-45102fc]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [custom.jar:git-Spigot-1ffab67-45102fc]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]`

**Comment by TWSSYesterday** [comment]
A lot of plugins aren't compatible with it at the moment, please pastebin the **ENTIRE** log file. Thanks

**Comment by RedLight66** [comment]
Yeah i know, I just warn developpers if their plugins aren't compatible in 1.12.prerelease. As the prerelease is destined to become the final 1.12 version :p
Sorry but I didn't have more logs about it.

**Comment by dumptruckman** [comment]
Ahh, this was fixed in build 718 actually. You're using 717.
