### ISSUE TITLE
No Such Method Exception and NPE on Use of /MVTP

### ISSUE THREAD

**Issue by Braleth** [Multiverse/Multiverse-Core#1820]
Testing MVTP teleports under 1.12 generated these errors in the console:

[11:57:30 INFO]: okamat issued server command: /mvtp UofA
[11:57:30 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.PacketPlayOutPlayerListHeaderFooter.<init>(net.minecraft.server.v1_12_R1.IChatBaseComponent)
[11:57:30 WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[11:57:30 WARN]:        at java.lang.Class.getConstructor(Class.java:1825)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.aI.<clinit>(TitleAPI.java:43)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.av.a(Tab.java:12)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.h.a(PlayChangeWorldListener.java:24)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:57:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:57:30 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[11:57:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[11:57:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:707)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:509)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:270)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[11:57:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:57:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:57:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:57:30 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[11:57:30 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:57:30 WARN]: java.lang.NullPointerException
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.aI.a(TitleAPI.java:88)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.av.a(Tab.java:12)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.h.a(PlayChangeWorldListener.java:24)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:57:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:57:30 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[11:57:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[11:57:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:707)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:509)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:270)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[11:57:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:57:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:57:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:57:30 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[11:57:30 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:57:30 WARN]: java.lang.NullPointerException
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.aI.a(TitleAPI.java:60)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.aw.a(Title.java:12)
[11:57:30 WARN]:        at com.pixelatedev.bossmessenger.impl.h.a(PlayChangeWorldListener.java:25)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:57:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:57:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:57:30 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[11:57:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[11:57:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[11:57:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:707)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:509)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:270)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[11:57:30 WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[11:57:30 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[11:57:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:57:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:57:30 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:57:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:57:30 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[11:57:30 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[11:57:30 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by dumptruckman** [comment]
`[11:57:30 WARN]: at com.pixelatedev.bossmessenger.impl.aI.(TitleAPI.java:43)` This implies the issue is not caused by Multiverse.
