### ISSUE TITLE
Spamming java error on console all the time.

### ISSUE THREAD

**Issue by comonier** [Multiverse/Multiverse-Core#1825]
Spigot 1.12 build: cd6ba67-a7d074c

Multiverse Inventory: #4​23 17/06/2017 02:57 (https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Inventories/)

18.06 13:12:41 [Server] ERROR Cannot load plugins/Multiverse-Inventories/worlds/world/TiFalcom.json
18.06 13:12:41 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:60) ~[?:?]
18.06 13:12:41 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:108) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:157) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:76) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:269) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:34) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:12:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
18.06 13:12:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
18.06 13:12:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
18.06 13:12:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
18.06 13:12:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:707) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:509) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:12:41 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:139) [EssentialsX-2.0.1.jar:?]
18.06 13:12:41 [Server] INFO at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.0.1.jar:?]
18.06 13:12:41 [Server] INFO at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:168) [EssentialsX-2.0.1.jar:?]
18.06 13:12:41 [Server] INFO at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:56) [EssentialsXSpawn-2.0.1.jar:?]
18.06 13:12:41 [Server] INFO at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) [EssentialsXSpawn-2.0.1.jar:?]

18.06 13:12:48 [Multicraft] Skipped 179 lines due to rate limit (30/s)

SPAMMING ALL TIME ON CONSOLE ALL PLAYERS

[13:19:25] [MV-Inv Profile Write Thread/ERROR]: Cannot load plugins/Multiverse-Inventories/groups/default/achu42.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
	at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:60) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
	at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:108) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:157) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:76) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:29) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
Caused by: com.onarandombox.multiverseinventories.util.json.parser.ParseException: Unexpected token 
 at position 53.
	at com.onarandombox.multiverseinventories.util.json.parser.JSONParserBase.parse(JSONParserBase.java:162) ~[?:?]
	at com.onarandombox.multiverseinventories.util.json.parser.JSONParserString.parse(JSONParserString.java:56) ~[?:?]
	at com.onarandombox.multiverseinventories.util.json.parser.JSONParserString.parse(JSONParserString.java:37) ~[?:?]
	at com.onarandombox.multiverseinventories.util.json.parser.JSONParser.parse(JSONParser.java:140) ~[?:?]
	at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:58) ~[?:?]
	... 8 more

**Comment by comonier** [comment]
8.06 13:26:13 [Server] ERROR Cannot load plugins/Multiverse-Inventories/groups/default/CapuzKing.json
18.06 13:26:13 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:60) ~[?:?]
18.06 13:26:13 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:26:13 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:108) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:157) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:76) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:26:13 [Server] INFO at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:29) [Multiverse-Inventories-2.5.0-SNAPSHOT.jar:?]
18.06 13:26:18 [Multicraft] Skipped 9 lines due to rate limit (30/s)
