### ISSUE TITLE
Error with saving stats

### ISSUE THREAD

**Issue by Majora555** [Multiverse/Multiverse-Core#1888]
Ive got this error when the server wants to save a player's stats however cause of the error down below it doesnt save it wich makes the server think that if a player leaves and rejoins its a new player wich has never gotten an item achievement or anything before while they have

[20:02:38 ERROR]: Couldn't save stats
java.io.FileNotFoundException: ./world/stats/87fcb63a-d70c-4487-9a99-86b317741c77.json (Permission denied)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_112]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_112]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_112]
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:360) ~[craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1981) ~[craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:2017) ~[craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ServerStatisticManager.b(SourceFile:52) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.savePlayerFile(PlayerList.java:311) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.savePlayers(PlayerList.java:1195) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:667) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Please help

**Comment by TWSSYesterday** [comment]
Fix the permissions for the server, use chmod/chown.

**Comment by Majora555** [comment]
what do you mean by that?

**Comment by TWSSYesterday** [comment]
Is it on a dedicated server that you manage?

**Comment by Majora555** [comment]
im sorry but i dont know what that means.
oh and i dont know if this helps but im running it on server.pro

**Comment by TWSSYesterday** [comment]
Contact them and show them the error, they should be able to set permissions correctly for you.

**Comment by Majora555** [comment]
i have but they told me to get pex and change the server to 1.12.2 spigot tough it doesnt work at al

**Comment by TWSSYesterday** [comment]
If they said that then I'd move away from them, doing that would not solve the issue.

**Comment by ryantheleach** [comment]
@TWSSYesterday It's my suspicion the help ticket read something like "I need help, I contacted multiverse and they said that you needed to set permissions for me"

@Majora555 try something like "Hey I've got a problem with the file system, My plugins are unable to create files. It comes up with the following error: "java.io.FileNotFoundException: ./world/stats/87fcb63a-d70c-4487-9a99-86b317741c77.json (Permission denied)" I believe this relates to a File System Permission, and I've been contacting the Multiverse Team who handle my multiple worlds plugin.

**Comment by Jadiction** [comment]
Closing ticket as this issue pertains to the server, not Multiverse itself. Please open a new ticket if this issue is still occurring in the latest versions.
