### ISSUE TITLE
/mv error

### ISSUE THREAD

**Issue by TomasGeilo** [Multiverse/Multiverse-Core#1931]
java.lang.NullPointerException
[18:11:26 WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:898)
[18:11:26 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:11:26 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:11:26 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:11:26 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:11:26 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[18:11:26 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[18:11:26 WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Jadiction** [comment]
What caused this error? What MC version are you running? Please refer to https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug when submitting bugs. Since this is a year old issue, I'm going to close it. If this error is still happening with the latest Multiverse versions, please open a new ticket with the additional information from the guidelines listed in the URL above.
