### ISSUE TITLE
1.13.2 Error

### ISSUE THREAD

**Issue by HeyNennMichChris** [Multiverse/Multiverse-Core#1944]
[19:32:28] [Server thread/WARN]: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:172)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:272)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:268)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getType(World.java:657)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getNMS(CraftBlock.java:54)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.util.CraftEvil.getType(CraftEvil.java:39)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:152)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[19:32:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:32:28] [Server thread/WARN]: Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
[19:32:28] [Server thread/WARN]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[19:32:28] [Server thread/WARN]: 	at java.util.Map.computeIfAbsent(Map.java:957)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[19:32:28] [Server thread/WARN]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:112)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:272)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:821)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:731)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:956)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:458)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[19:32:28] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[19:32:28] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
[19:32:28] [Server thread/WARN]: 	... 16 more
[19:32:28] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[19:32:28] [Server thread/WARN]: 	at de.yellowphoenix18.realistic.generators.MainGenerator.generateChunkData(MainGenerator.java:54)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:61)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskBase.a(SourceFile:13)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:78)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1)
[19:32:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[19:32:28] [Server thread/WARN]: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[19:32:28] [Server thread/WARN]: 	... 87 more

**Comment by EbonJaeger** [comment]
Are you using a 3rd-party terrain generator?

**Comment by HeyNennMichChris** [comment]
i use the realistic world generator
https://www.spigotmc.org/resources/realisticworldgenerator.15905/

**Comment by EbonJaeger** [comment]
Realistic World Generator is not updated to 1.13, and the error is actually coming from it (the second Caused by).

**Comment by FernFerret** [comment]
@EbonJaeger is correct, this is not caused by Multiverse, you can see the full exception (from what you posted) here:

```
[19:32:28] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[19:32:28] [Server thread/WARN]: 	at de.yellowphoenix18.realistic.generators.MainGenerator.generateChunkData(MainGenerator.java:54)
[19:32:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:61)
```

**Comment by HeyNennMichChris** [comment]
ok perfect, thx
