### ISSUE TITLE
NoClassDefFound EntryFee on start-up

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#1959]
Spigot 1.13.2
MV-Core 2.7.0-SNAPSHOT-b743
WE 7.0.0-b4003
WG 7.0.0-b1788
```
[08:35:28] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.7.0-SNAPSHOT-b743
[08:35:28] [Server thread/ERROR]: Could not call constructor 'public com.onarandombox.MultiverseCore.configuration.EntryFee(java.util.Map)' of class com.onarandombox.MultiverseCore.configuration.EntryFee for deserialization
java.lang.NoClassDefFoundError: de/themoep/idconverter/IdMappings
        at com.onarandombox.MultiverseCore.configuration.EntryFee$EntryFeeCurrencySerializor.deserialize(EntryFee.java:82) ~[?:?]
        at com.onarandombox.MultiverseCore.configuration.EntryFee$EntryFeeCurrencySerializor.deserialize(EntryFee.java:74) ~[?:?]
        at me.main__.util.multiverse.SerializationConfig.SerializationConfig.loadValues(SerializationConfig.java:222) ~[?:?]
        at me.main__.util.multiverse.SerializationConfig.SerializationConfig.<init>(SerializationConfig.java:185) ~[?:?]
        at com.onarandombox.MultiverseCore.configuration.EntryFee.<init>(EntryFee.java:31) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at com.onarandombox.MultiverseCore.MultiverseCore.migrateWorldConfig(MultiverseCore.java:586) [Multiverse-Core-2.7.0-b743.jar:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:510) [Multiverse-Core-2.7.0-b743.jar:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309) [Multiverse-Core-2.7.0-b743.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at com.drcnetwork.particles.Particles.checkMultiverse(Particles.java:72) [Particles-3.0.jar:?]
        at com.drcnetwork.particles.Particles.onEnable(Particles.java:44) [Particles-3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: de.themoep.idconverter.IdMappings
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar-2019-01-21-0807:git-Spigot-f56e2e7-1a64d4a]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 62 more
```
30 times...

**Comment by SlimeDog** [comment]
Confirmed resolved in MC 2.7.0-b744
