### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by StossenHDYT** [Multiverse/Multiverse-Core#1968]
[16:31:25] [Server thread/INFO]: StossenHDYT issued server command: /mv create CityBuildM normal -g PlotMe-DefaultGenerator
[16:31:25] [Server thread/INFO]: StossenHDYT: Starting creation of world 'CityBuildM'...[m
[16:31:25] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'CityBuildM' - Env: NORMAL - Type: NORMAL & generator: PlotMe-DefaultGenerator
[16:31:25] [Server thread/INFO]: -------- World Settings For [CityBuildM] --------
[16:31:25] [Server thread/INFO]: Mob Spawn Range: 4
[16:31:25] [Server thread/INFO]: Anti X-Ray: true
[16:31:25] [Server thread/INFO]: 	Engine Mode: 1
[16:31:25] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[16:31:25] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[16:31:25] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:31:25] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:31:25] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:31:25] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:31:25] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:31:25] [Server thread/INFO]: Random Lighting Updates: false
[16:31:25] [Server thread/INFO]: Structure Info Saving: true
[16:31:25] [Server thread/INFO]: Sending up to 10 chunks per packet
[16:31:25] [Server thread/INFO]: Max Entity Collisions: 8
[16:31:25] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:31:25] [Server thread/INFO]: Max TNT Explosions: 100
[16:31:25] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:31:25] [Server thread/INFO]: Item Despawn Rate: 6000
[16:31:25] [Server thread/INFO]: Item Merge Radius: 2.5
[16:31:25] [Server thread/INFO]: Arrow Despawn Rate: 1200
[16:31:25] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:31:25] [Server thread/INFO]: View Distance: 10
[16:31:25] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:31:25] [Server thread/INFO]: Chunks to Grow per Tick: 650
[16:31:25] [Server thread/INFO]: Clear tick list: false
[16:31:25] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:31:25] [Server thread/INFO]: Preparing start region for level 7 (Seed: 3769497700569356962)
[16:31:25] [Server thread/INFO]: [WorldGuard] Default configuration file written: /root/Server1/plugins/WorldGuard/worlds/CityBuildM/config.yml
[16:31:25] [Server thread/INFO]: [WorldGuard] Default configuration file written: /root/Server1/plugins/WorldGuard/worlds/CityBuildM/blacklist.txt
[16:31:25] [Server thread/INFO]: [WorldGuard] (CityBuildM) TNT ignition is PERMITTED.
[16:31:25] [Server thread/INFO]: [WorldGuard] (CityBuildM) Lighters are PERMITTED.
[16:31:25] [Server thread/INFO]: [WorldGuard] (CityBuildM) Lava fire is blocked.
[16:31:25] [Server thread/INFO]: [WorldGuard] (CityBuildM) Fire spread is UNRESTRICTED.
[16:31:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'CityBuildM'
[16:31:25] [Server thread/ERROR]: Could not pass event WorldLoadEvent to Multiverse-Core v2.5.0-b727
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:933) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:464) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466) [Multiverse-Core-2.5.0.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268) [Multiverse-Core-2.5.0.jar:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) [Multiverse-Core-2.5.0.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.0.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.0.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.0.jar:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) [Multiverse-Core-2.5.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: net.minecraft.server.v1_8_R3.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:403) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 29 more
Caused by: java.lang.NullPointerException
	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:83) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:142) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:403) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 29 more
[16:31:25] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Exception generating new chunk
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[16:31:25] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[16:31:25] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[16:31:25] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[16:31:25] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:31:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:31:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:31:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:31:25] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[16:31:25] [Server thread/WARN]: 	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47)
[16:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:83)
[16:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:142)
[16:31:25] [Server thread/WARN]: 	... 32 more
[16:31:52] [Server thread/INFO]: StossenHDYT issued server command: /mvlist
[16:32:15] [Server thread/INFO]: StossenHDYT issued server command: /mv create CityBuildM normal -g PlotMe-DefaultGenerator
[16:32:37] [Server thread/INFO]: StossenHDYT issued server command: /mvimport CityBuildM
[16:32:50] [Server thread/INFO]: StossenHDYT issued server command: /mvimport CityBuildMnormal
[16:32:54] [Server thread/INFO]: StossenHDYT issued server command: /mvimport CityBuildM normal
[16:32:54] [Server thread/INFO]: StossenHDYT: Starting import of world 'CityBuildM'...[m
[16:32:54] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'CityBuildM' - Env: NORMAL - Type: null
[16:32:54] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Exception generating new chunk
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:152)
[16:32:54] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[16:32:54] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[16:32:54] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[16:32:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:32:54] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:32:54] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:32:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:32:54] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[16:32:54] [Server thread/WARN]: 	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47)
[16:32:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:83)
[16:32:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:142)
[16:32:54] [Server thread/WARN]: 	... 32 more

**Comment by dumptruckman** [comment]
It looks like this bug is being caused by plotme. Make sure you the version of plotme you're using is compatible with your server version.
