### ISSUE TITLE
Errors with Multiverse-Core on 1.13.2 server

### ISSUE THREAD

**Issue by ktg5** [Multiverse/Multiverse-Core#1970]
When I try to do any command in Multiverse-Core I just get this error...

`17.02 20:02:22 [Server] WARN java.lang.NullPointerException
17.02 20:02:22 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
17.02 20:02:22 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
17.02 20:02:22 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138)
17.02 20:02:22 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:684)
17.02 20:02:22 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:670)
17.02 20:02:22 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:423)
17.02 20:02:22 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:383)
17.02 20:02:22 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792)
17.02 20:02:22 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695)
17.02 20:02:22 [Server] WARN at java.lang.Thread.run(Unknown Source)
17.02 20:02:22 [Server] INFO An internal error occurred when attempting to perform this command.
17.02 20:02:22 [Server] INFO Details were printed to the server console and logs, please add that to your bug report.`

If there is a way to fix this, please let me know.
Thanks, ktg.

**Comment by ktg5** [comment]
nvm, just needed to update lmao.
