### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Cypaubr** [Multiverse/Multiverse-Core#1980]
```
Could not pass event PlayerInteractEvent to Multiverse-Portals v3.0.0-SNAPSHOT-b788
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-518
206a-a5b9c7b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-51820
6a-a5b9c7b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-51
8206a-a5b9c7b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-51
8206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:2
99) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:2
66) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot.jar:git-S
pigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot.jar:git-Spigot-518
206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot.jar:git-Spigot-518206a-a5b9
c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot.jar:git-Spigot-518206a-a5b9
c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-518206a-a5b
9c7b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot.jar:git-Spigot-518206a
-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-518206a
-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot.jar:git-Spigot-518206a
-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-51820
6a-a5b9c7b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerInteract(MVPPlayerListener.java:168
) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-518
206a-a5b9c7b]
        ... 18 more
```

**Comment by imrowin** [comment]
Same issue, all the time.

**Comment by imrowin** [comment]
Think I found a temp solution, what version of spigot are you running?

**Comment by imrowin** [comment]
Basically instead of using the latest dev build, just go on bukkit Multiverse-core or SpigotMC, and download the correct multiverse-core for your version.

**Comment by Matocolotoe** [comment]
I confirm I have this issue too.

**Comment by dumptruckman** [comment]
As mentioned, make sure your MV-Core and MV-Portals versions are matching. Also, please open this ticket on [the correct issue tracker](https://github.com/Multiverse/Multiverse-Portals/issues) if you continue to have this problem.

**Comment by BrettplayMC** [comment]
Gonna be like 3:22 when I get out

Sent from my iPad

On Apr 15, 2019, at 1:41 PM, Jeremy Wood <notifications@github.com> wrote:

Closed #1980 <https://github.com/Multiverse/Multiverse-Core/issues/1980>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Multiverse/Multiverse-Core/issues/1980#event-2277522434>,
or mute the thread

**Comment by Matocolotoe** [comment]
Happened to me though I don't have MV-Portals

**Comment by IMcrafter** [comment]
I've got the same issue. 2020 is now, Still no solutions, guys?

**Comment by MattixNow** [comment]
Up ?

**Comment by XavierDare** [comment]
Same problem it spams console almost every time someone says something
