### ISSUE TITLE
About PlayerPortalEvent（MineCraft1.14.1）

### ISSUE THREAD

**Issue by BackWheel** [Multiverse/Multiverse-Core#1998]
[20:42:51 ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v3.0.0-SNAPSHOT-b761
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor276.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-22]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-22]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:843) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2160) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:393) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:365) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2273) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1198) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057) ~[patched_1.14.1.jar:git-Paper-22]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902) ~[patched_1.14.1.jar:git-Paper-22]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by ThexXTURBOXx** [comment]
Can confirm this bug. Very annoying, because it breaks uSkyblock as well

**Comment by TBG-FR** [comment]
Seem to be appearing with both `2.5.0` and `3.0.0-b760 (alpha)` versions.

**Comment by TheKinrar** [comment]
This is due to the removal of the TravelAgent API from the Spigot project (see https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-1-development-builds.369724/) - and also completely breaks MV-NP as it heavily relied on it for generating portals.

**Comment by Jadiction** [comment]
Hello, Multiverse is aware of these errors and will be working on a 1.14 compatibility update soon.


A message from dumptruckman:

I just want to let you know that I understand there are some issues with Multiverse running on 1.14. The reason behind this is the removal of something called the TravelAgent. Because this was removed, some stuff broke related to nether and end portals. In particular, Multiverse-NetherPortals is not working at all.

You should all know that 1.14, 1.14.1, and 1.14.2 have been full of problems in general. What you may not know is that TravelAgent is going to come back. When it does, most of the things that 1.14 broke in MV will no longer be broken. Since I have so little time to devote to this project, it seems to be in my best interest to just wait for that to happen rather than make a bunch of changes I will need to change back later. I know you're all anxious to get your servers working perfectly for 1.14 but from what I hear, 1.14 is just far from perfect itself right now. Please be patient while we wait for better days.

**Comment by Jadiction** [comment]
This appears to be fixed in the latest Multiverse dev build (4.0.0) - https://ci.onarandombox.com/job/Multiverse-Core/
