### ISSUE TITLE
Wont Generate or Import World

### ISSUE THREAD

**Issue by TheWalrusGamer** [Multiverse/Multiverse-Core#2003]
While Trying to Create a New World called "Home" the server tells me that it is corrupted, before being generated. The Other issue (I Dont have a log for this one) is that it says it contains a special character, when it dosent. Im confused, and could use some help.

mv create Home NORMAL -t flat
[18:15:40] [Server thread/INFO]: CONSOLE: Starting creation of world 'Home'...
[18:15:40] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'Home' - Env: NORMAL - Type: FLAT
[18:15:40] [Server thread/WARN]: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Home
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:188)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DimensionManager.register(DimensionManager.java:23)
[18:15:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:926)
[18:15:40] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:467)
[18:15:40] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:269)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[18:15:40] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:900)
[18:15:40] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:15:40] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
[18:15:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:686)
[18:15:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:672)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:406)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:371)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:912)
[18:15:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:766)
[18:15:40] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:15:40] [Server thread/ERROR]: [Multiverse-Core] The world 'Home' could NOT be loaded because it contains errors and is probably corrupt!
[18:15:40] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Home'
[18:15:40] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[18:15:40] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'Home'
[18:15:40] [Server thread/INFO]: CONSOLE: FAILED.

**Comment by Diamondman121314** [comment]
You need to update to the latest version of whatever you're using (Spigot, Paper, etc) as it contains the fix to allow you to create worlds with uppercase names.
