### ISSUE TITLE
Java heap space error on 1.14.2 version

### ISSUE THREAD

**Issue by kanyunhk** [Multiverse/Multiverse-Core#2018]
This error has never pop up in the previous versions (versions below 1.14), upon updating to 1.14.2, it starts having this error.

Using the latest MV-Core Jenkins build (b764) and latest Spigot 1.14.2 as of 2019-06-14.

```
[13:20:42] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.0.0-SNAPSHOT-b764 (Is it up to date?)
java.lang.OutOfMemoryError: Java heap space
>       at java.util.ArrayList.<init>(ArrayList.java:152) ~[?:1.8.0_131]
>       at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:190) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagList.load(SourceFile:62) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:114) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:83) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:24) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.Convertable.a(SourceFile:155) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.Convertable.a(SourceFile:139) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.Convertable.b(SourceFile:127) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.Convertable.isConvertable(SourceFile:117) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.MinecraftServer.convertWorld(MinecraftServer.java:233) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:918) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.Bukkit.createWorld(Bukkit.java:458) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
>       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
>       at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
>       at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
>       at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315) ~[?:?]
>       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
>       at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) ~[spigot.jar:git-Spigot-df0eb25-4090d01]
```

**Comment by Jadiction** [comment]
I may be wrong, but it looks like the server ran out of memory while loading the plugin.

**Comment by kanyunhk** [comment]
I do suspect that but I have already tried allocating a lot more memory to the server and it's still erroring out, (from 3GB to 6GB, the whole machine has 16GB RAM), so I'm not entirely sure what went wrong during the loading process and try here to see if there are any luck finding fixes

**Comment by jennasisis** [comment]
If the machine has 16GB, try upping that amount to 8GB. I can run a server with 8GB and still have room to spare on my machine

**Comment by kanyunhk** [comment]
I have tried assigning 8GB to the server and it is still giving me the same error. When trying I have also upgraded to the latest Spigot build 1.14.3  as of 2019-07-02.

**Comment by dumptruckman** [comment]
Sounds like you have a memory leak. It's either the server software itself or some plugin.

**Comment by dumptruckman** [comment]
Ah, sorry, it looks like it's specifically happening when converting the world to the 1.14 format. Something is wrong with your world or the 1.14 server software. You could try loading the world in single player and seeing if it is able to properly convert it.

**Comment by kanyunhk** [comment]
Thanks for your reply, I will try to convert the world to 1.14 format, didn't think of the problem in this way, thanks!
