### ISSUE TITLE
Unable to load world

### ISSUE THREAD

**Issue by smilet** [Multiverse/Multiverse-Core#2041]
Multiverse is not able to load my old worlds. I can load them one by one without multiverse without issues. I have tried checking (takes ages) with the regionfixer but without luck.

[08:25:04] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.0.0-b766
[08:25:04] [Server thread/WARN]: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:ADV
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:189)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DimensionManager.a(DimensionManager.java:23)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:950)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:458)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[08:25:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[08:25:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[08:25:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[08:25:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[08:25:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[08:25:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[08:25:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
[08:25:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[08:25:04] [Server thread/ERROR]: [Multiverse-Core] The world 'ADV' could NOT be loaded because it contains errors and is probably corrupt!
[08:25:04] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'ADV'
[08:25:04] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[08:25:05] [Server thread/WARN]: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:KREA2
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IRegistry.a(SourceFile:189)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DimensionManager.a(DimensionManager.java:23)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:950)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:458)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[08:25:05] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[08:25:05] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[08:25:05] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[08:25:05] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[08:25:05] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[08:25:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[08:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
[08:25:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[08:25:05] [Server thread/ERROR]: [Multiverse-Core] The world 'KREA2' could NOT be loaded because it contains errors and is probably corrupt!
[08:25:05] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'KREA2'

**Comment by EbonJaeger** [comment]
Minecraft now requires all world names to be lowercase. I think at some point in 1.14, Spigot made a change to allow uppercase letters in world names again.

**Comment by smilet** [comment]
Yes, both is true. Thanks for the reply.
But doesn't explain why multiverse doesn't work since mc/spigot is working.
I guess it could means that I have to rename my worlds.
It is a huge and risky job, so I will wait with the update and look around for other mulitiworld options.

**Comment by EbonJaeger** [comment]
It does explain it because I'm willing to bet the Spigot version you're using is from *before* they re-allowed uppercase letters. The first error message pretty much says it, the name doesn't match the format of all lowercase letters, numbers, `.`, or `-`.

**Comment by smilet** [comment]
Alright, thanks for the hint!

**Comment by smilet** [comment]
You where right of course. The hint made me succeed by going upstream and it turned out that the main issue was old spigot but also an old Java-Version making loading stuck.

This article describes this part of my troubles. Thanks!

**Comment by smilet** [comment]
https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-153634
