### ISSUE TITLE
Error when create a new world

### ISSUE THREAD

**Issue by DarkValPT** [Multiverse/Multiverse-Core#2055]
[21:22:53] [Server thread/INFO]: DarkVal issued server command: /mv create newworld normal -t
[21:22:53] [Server thread/INFO]: DarkVal: Starting creation of world 'newworld'...[m
[21:22:53] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'newworld' - Env: NORMAL - Type: NORMAL
[21:22:53] [Server thread/WARN]: java.io.FileNotFoundException: ./newworld/session.lock (No such file or directory)
[21:22:53] [Server thread/WARN]: 	at java.io.FileOutputStream.open0(Native Method)
[21:22:53] [Server thread/WARN]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:22:53] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:22:53] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.h(WorldNBTStorage.java:47)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.<init>(WorldNBTStorage.java:41)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ServerNBTManager.<init>(SourceFile:19)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:871)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[21:22:53] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:22:53] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[21:22:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:22:53] [Server thread/WARN]: java.lang.RuntimeException: Failed to check session lock for world located at ./newworld, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.h(WorldNBTStorage.java:57)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.<init>(WorldNBTStorage.java:41)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ServerNBTManager.<init>(SourceFile:19)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:871)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[21:22:53] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[21:22:53] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:22:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[21:22:53] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:22:53] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[21:22:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[21:22:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:22:53] [Server thread/ERROR]: [Multiverse-Core] The world 'newworld' could NOT be loaded because it contains errors and is probably corrupt!
[21:22:53] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'newworld'
[21:22:53] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[21:22:53] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'newworld'
[21:22:53] [Server thread/INFO]: DarkVal: FAILED.[m

**Comment by dumptruckman** [comment]
You have a file system error. Does the `newworld` directory already exist? If not, do you have write permissions on the server directory?

**Comment by DarkValPT** [comment]
how i can get that permission ?

**Comment by dumptruckman** [comment]
You will need to seek such answers elsewhere. It has nothing to do with Multiverse.

**Comment by dumptruckman** [comment]
You might want to look into the spigot irc channel.
