### ISSUE TITLE
Error occurred while enabling Multiverse-Core v4.1.1-SNAPSHOT-b777 (Is it up to date?)

### ISSUE THREAD

**Issue by B4TT3RY** [Multiverse/Multiverse-Core#2090]
```
[13:50:52 ERROR]: Error occurred while enabling Multiverse-Core v4.0.0-SNAPSHOT-b765 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:353) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:342) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-175]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
[13:50:52 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.0.0-SNAPSHOT-b765
```
I'm using on OpenJDK8 OpenJ9, git-paper-176

**Comment by Jadiction** [comment]
Buscript is deprecated in Java 12, so this shouldn't be your issue. Maybe try redownloading the plugin and ensuring it's not corrupted. To clarify, you're on MC 1.14.4?

**Comment by B4TT3RY** [comment]
> Buscript is deprecated in Java 12, so this shouldn't be your issue. Maybe try redownloading the plugin and ensuring it's not corrupted. To clarify, you're on MC 1.14.4?

not Java 12, Java 8.
I fixed it by modifying the code.

**Comment by AkashFires** [comment]
Hello, I have the same problem since i'm using  OpenJ9, what exactly did you change? 
the difference that OpenJ9 make is immense therefore my need to fix this multiverse problem. 
I'm using 1.15.2 right now

**Comment by AkashFires** [comment]
The problem was fixed by installing OpenJ9 JDK 11 container instead of 8.
