### ISSUE TITLE
Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-b719

### ISSUE THREAD

**Issue by TehZombiJesus** [Multiverse/Multiverse-Core#2101]
Hi,

I just got this error on my server, can anyone help me out?

`[Server thread/ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-b719
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:763) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2070) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:374) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:346) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2218) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:162) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:399) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:140) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:224) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1091) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        ... 19 more`

Best Regards,
- TehZombiJesus

**Comment by Jadiction** [comment]
MC version?

**Comment by TehZombiJesus** [comment]
1.14.4

**Comment by Jadiction** [comment]
2.5 is very outdated for 1.14.4, update all your Multiverse plugins.

**Comment by Jadiction** [comment]
https://ci.onarandombox.com/job/Multiverse-Core/

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
