### ISSUE TITLE
MV issue occurance - MultiverseCore.utils.UnsafeCallWrapper.

### ISSUE THREAD

**Issue by EchocallingEarth** [Multiverse/Multiverse-Core#2110]
Please find attached the full log at start up.
The error wraps 3 times in a row and upon further investigation seems directly related to MV.

Please review and assist if possible.
Error begins wrapping at [21:35:35] - Line 888 with warning before at [21:35:34] - line 861

[](https://pastebin.com/At2f0mdF)

Minecraft version 1.14.4
Paper

Thank you
Echo

**Comment by Jadiction** [comment]
Why does it seem related to MV? You'd need to provide the full error?

**Comment by EchocallingEarth** [comment]
https://pastebin.com/At2f0mdF

    at com.onarandombox.MultiverseCore.utils.WorldManager$3.call(WorldManager.java:443) ~[?:?]
    at com.onarandombox.MultiverseCore.utils.UnsafeCallWrapper.wrap(UnsafeCallWrapper.java:32) ~[?:?]
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:440) ~[?:?]
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315) ~[?:?]

Additional testing with other plugins removed and the error still shows
Also sorry as it seems that the pastbin link was removed in the previous which possibly did not help.

I will do my best to provide as much info as possible, so as to resolve this error/issue

Again thank you
Echo

**Comment by Jadiction** [comment]
It seems to be plotsquared. The Multiverse error looks like it's just saying it can't load the plotsquared world.
