### ISSUE TITLE
[12:49:14 ERROR]: Could not pass event PlayerInteractEvent to Multiverse-Core v4.1.0-b775

### ISSUE THREAD

**Issue by Afgewezen** [Multiverse/Multiverse-Core#2116]
[12:49:14 ERROR]: Could not pass event PlayerInteractEvent to Multiverse-Core v4.1.0-b775
java.lang.NoSuchFieldError: END_PORTAL_FRAME
at com.onarandombox.MultiverseCore.listeners.MVPortalListener.portalForm(MVPortalListener.java:74) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[server.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[server.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by tdubz1** [comment]
Yes, I get this error as well. I am running a 1.8.8 Spigot Server.

**Comment by FaiqGaming** [comment]
Yes, i get the error too in my spigot server 1.12.2

**Comment by Jadiction** [comment]
I haven't seen this error yet, but it's likely due to using an outdated version of Minecraft with an updated Multiverse. Multiverse isn't updated with outdated versions in mind.

**Comment by codergautam** [comment]
Using this version fixed this issue: https://www.spigotmc.org/resources/multiverse-core-for-1-9-1-10-1-11-1-12.23327/
