### ISSUE TITLE
error  on enable

### ISSUE THREAD

**Issue by Lufrut** [Multiverse/Multiverse-Core#2121]
> [20:35:08] [Server thread/INFO]: [Multiverse-Core] 6 - World(s) loaded.
> [20:35:08] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:351) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [server.jar:git-Spigot-56f8471-7554e08]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
And it`s probably reason why server has stopped every time when  i tried run it

**Comment by Jadiction** [comment]
What MC version are you running? If it's 1.8 then Multiverse 4.1.0 will not work for it.

**Comment by Lufrut** [comment]
Paper 1.14.4

**Comment by Lufrut** [comment]
Sorry , i forgot about this ticket , i just waited when new paper going on , and install it  and after it this issue was fixed.
