### ISSUE TITLE
MV stating that world cannot be loaded

### ISSUE THREAD

**Issue by Mentobi** [Multiverse/Multiverse-Core#2127]
I have an old 1.8 World that I'm trying to import in. 
I ran it through the optimizer to bring it up to 1.44.4. And it loads as a SP and it loads in the normal Generic Vanilla MC server. 
But when I load it into my server, it loads but crashes the server. 
when the server starts I get this. 

I did as the error suggested and ran the world corrupter fix tool as listed in the error and it found no issues. 

I have TWO worlds with this issue. 

I'm running the most current version of Essentialsx (With XMP not configured) and worldedit. both of these worlds used to have a stupid amount of command blocks, and I've disabled the use of them because I was afraid they were causing issues. 

06.11 02:16:00 [Server] WARN java.lang.NullPointerException
06.11 02:16:00 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1004)
06.11 02:16:00 [Server] WARN at org.bukkit.Bukkit.createWorld(Bukkit.java:492)
06.11 02:16:00 [Server] WARN at org.bukkit.WorldCreator.createWorld(WorldCreator.java:284)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:404)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
06.11 02:16:00 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
06.11 02:16:00 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
06.11 02:16:00 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
06.11 02:16:00 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:910)
06.11 02:16:00 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
06.11 02:16:00 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
06.11 02:16:00 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158)
06.11 02:16:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
06.11 02:16:00 [Server] WARN at java.lang.Thread.run(Thread.java:748)
06.11 02:16:00 [Server] ERROR [Multiverse-Core] The world 'castle' could NOT be loaded because it contains errors and is probably corrupt!
06.11 02:16:00 [Server] ERROR [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'castle'
06.11 02:16:00 [Server] ERROR [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer

**Comment by Mentobi** [comment]
Fixed this by making each world the primary world the server starts up too, then reverting back the one where I wanted it to start. This allowed them to load for some reason.
