### ISSUE TITLE
Error when enabling Multiverse-Core 

### ISSUE THREAD

**Issue by Adib23704** [Multiverse/Multiverse-Core#2131]
I downloaded the latest version of the **Multiverse-Core** from **bukkit's** website and I am getting this error when I start the server...

```
Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:351) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-226]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-226]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-226]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-226]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
[Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775
```

**Comment by Jadiction** [comment]
If your MC version is outdated then Multiverse 4.1.0 likely isn't compatible with it.  You could look for outdated versions of Multiverse on bukkit's website.

**Comment by PinoyLifeCraft** [comment]
But I am using the latest stable papermc for 1.15.2.

**Comment by benwoo1110** [comment]
your error message shows `minecraft.server.v1_14_R1` which is server version of 1.14 or 1.14.X.

**Comment by dumptruckman** [comment]
This is typically cause by using Java 12 or later.
