### ISSUE TITLE
/mv import command doesn't work

### ISSUE THREAD

**Issue by PasteYT** [Multiverse/Multiverse-Core#2136]
Bonjour,
J'ai un serveur mohist 1.12.2 sur lequel j'ai ajouté multiverse core.
Quand je fais la commande /mv import la map que je veux commence à s'importer mais un message d'erreur s'affiche sur la console au bout de quelques secondes:

>mv import Killhouse NORMAL
> [07:06:37 INFO]: CONSOLE: Starting import of world 'Killhouse'...
> [07:06:37 INFO]: [Multiverse-Core] Loading World & Settings - 'Killhouse' - Env: NORMAL - Type: null
> [07:06:38 WARN]: Unexpected exception while parsing console command "mv import Killhouse NORMAL"
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.4-b527
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:ef4a0be]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[SimpleCommandMap.class:ef4a0be]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:ef4a0be]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:726) [CraftServer.class:ef4a0be]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:509) [nz.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at net.minecraft.world.DifficultyInstance.func_180169_a(SourceFile:83) ~[ua.class:?]
at net.minecraft.world.DifficultyInstance.<init>(SourceFile:19) ~[ua.class:?]
at net.minecraft.world.World.func_175649_E(World.java:4216) ~[amu.class:?]
at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:349) ~[anb.class:?]
at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:472) ~[aze.class:?]
at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.func_185931_b(NormalChunkGenerator.java:44) ~[NormalChunkGenerator.class:ef4a0be]
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1206) ~[axw.class:?]
at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1185) ~[axw.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:168) ~[on.class:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:580) ~[CraftWorld.class:ef4a0be]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:472) ~[CraftWorld.class:ef4a0be]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.setKeepSpawnInMemory(CraftWorld.java:1582) ~[CraftWorld.class:ef4a0be]
at com.onarandombox.MultiverseCore.MVWorld.setActualKeepSpawnInMemory(MVWorld.java:260) ~[Multiverse-Core-2.4.jar:?]
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:223) ~[Multiverse-Core-2.4.jar:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:150) ~[Multiverse-Core-2.4.jar:?]
at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147) ~[Multiverse-Core-2.4.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[Multiverse-Core-2.4.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[Multiverse-Core-2.4.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[Multiverse-Core-2.4.jar:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476) ~[Multiverse-Core-2.4.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:ef4a0be]
... 8 more

J'ai essayé plusieurs versions du plugin je suis actuellement en 2.4
Je ne pense pas que ce soit la map car j'en ai essayé plusieurs que j'avais ouvertes en solo avant donc de la bonne version.
Merci d'avance pour votre aide.
Pasté

**Comment by blubberdiblub** [comment]
Which other versions did you try?

For a 1.12 server, the appropriate Multiverse version is most likely 2.5:
https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by PasteYT** [comment]
J'ai essayé la 2.5 spigot et la 4.1.0 bukkit

**Comment by PasteYT** [comment]
Je ne sais pas si ça peut poser souci mais j'ai été oblobligé de mettre la map dans le dossier de la map de base de mon serveur car en déposant directement la map dans le dossier du serveur le plugin ne la trouvait pas.

**Comment by Jadiction** [comment]
Your MC version is outdated then Multiverse 4.1.0 likely isn't compatible with it. You could look for outdated versions of Multiverse on bukkit's website as blubberdiblub suggested.
