### ISSUE TITLE
Error when enabling the multiverse-core

### ISSUE THREAD

**Issue by Adib23704** [Multiverse/Multiverse-Core#2146]
Here is my log

`Error occurred while enabling Multiverse-Core v4.0.0-b766 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:356) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:342) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
[Multiverse-Core] Disabling Multiverse-Core v4.0.0-b766`

**Comment by najimc** [comment]
same problem :/

**Comment by najimc** [comment]
Issue Fixed

Use an old version of multiverse
https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by Adib23704** [comment]
> Issue Fixed
> 
> Use an old version of multiverse
> https://dev.bukkit.org/projects/multiverse-core/files/2428161

It will work correctly?
for 1.15?

**Comment by Jadiction** [comment]
Use the latest version from dev builds - https://ci.onarandombox.com/job/Multiverse-Core/
