### ISSUE TITLE
multiverse core and openj9

### ISSUE THREAD

**Issue by Kbryst** [Multiverse/Multiverse-Core#2198]
So I apologize, I'm not the most technical person. I hope I get all the info needed.

My server is currently using the following image for its docker container:
quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-openj9

Whenever it uses openj9 it seems that multiverse-core isn't able to start up. 

I found some off-post somewhere that said multiverse and openj9 don't play nicely together so I changed my docker container image to quay.io/pterodactyl/core:java

This did fix it for me, but I can't keep this fix.
When I changed the image the server performance tanked really badly, is there another way I can get multiverse-core to work?

`[02:01:31] [Server thread/INFO]: [Multiverse-Core] 5 - World(s) loaded.
[02:01:31] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.1-SNAPSHOT-b40 (Is it up to date?)
java.lang.NullPointerException: null
	at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
	at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
	at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:353) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-137]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-137]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-137]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
[02:01:31] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.1-SNAPSHOT-b40`

**Comment by benwoo1110** [comment]
If you are using liunx try using OpenJDK 11 64 bit instead. Not sure if java 11 is supported, but its should be backward compatible with java 8 anyways

**Comment by Kbryst** [comment]
I did switch to that and it works :) thank you!
