### ISSUE TITLE
Sometimes MV Fails to Enable

### ISSUE THREAD

**Issue by MidnightSugar** [Multiverse/Multiverse-Core#2215]
When I add in plotsquared worlds, I get this error:

```
>.... [15:31:12 ERROR]: Error occurred while enabling Multiverse-Core v4.1.1-SNAPSHOT-b777 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:353) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-162]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
>.... [15:31:12 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.1-SNAPSHOT-b777
```

I took plotsquared off the server, and the plugin loaded.

**Comment by benwoo1110** [comment]
Will require more testing with plotsquared to see if this bug is reproducible. If anyone knows the steps to reproduce, do add comments on how to reproducible.

**Comment by nicegamer7** [comment]
Maybe you can help us out by answering these questions:
- Which host you are using (or if you're self hosting, what operating system)
- Which version of Java your server runs on
- The output of /version
- The output of /mv version
- What version of PlotSquared did you have

**Comment by nicegamer7** [comment]
Here is some info from another user:
- Host: Titan Nodes
- Java 8
- `/version`: Paper Build 334
- Plugin Causing: Custom

**Comment by nicegamer7** [comment]
Here is some info from another user:

Host: DedicatedMC
Java 8
/version: Paper Build 335
Plugin Causing: Boss

**Comment by nicegamer7** [comment]
In all three cases, it seems the plugin causing Buscript to fail to initialize also uses the ScriptEngine class. For the time being, here is a build of MV that tries to handle the situation gracefully.

[Multiverse-Core-4.1.1-SNAPSHOT.zip](https://github.com/Multiverse/Multiverse-Core/files/4745641/Multiverse-Core-4.1.1-SNAPSHOT.zip)

**Comment by MidnightSugar** [comment]
The provided build of MV here fixed my issue. It also worth mentioning that switching from Java 8 to Java 11 (never tested any other java version) also fixed my problem.

But I have some plugins that don't yet support java 11, so I will be using the provided build with java 8.
