### ISSUE TITLE
MV set generator but without the ID, causing NPE during PlayerJoinEvent

### ISSUE THREAD

**Issue by gamerover98** [Multiverse/Multiverse-Core#2230]
After clean installation, when a player joins, the plugin throws a NullPointerException.

**Console output**
```
[18:57:34] [Server thread/WARN]: [Multiverse-Core] The world specified as the spawn world (world) did not exist!!
[18:57:34] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Multiverse-Core v4.1.0-b775
java.lang.NullPointerException: null
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerJoin(MVPlayerListener.java:116) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor32.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-161]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-161]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-161]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

### **Versions**

- **Minecraft**: 1.15.2
- **Paper**: 77
- **Multiverse-Core**: 4.1.0-b775

**Comment by benwoo1110** [comment]
can you send your full server log via pastebin.com?

**Comment by gamerover98** [comment]
Ok, I've found the issue. In the auto-generated worlds.yml config file, the default generator as same as bukkit.yml world generator but without the ID.

**bukkit.yml**
```
worlds:
  world:
    generator: ParadiseLand:eden.yml
```

**generated worlds.yml**
```
worlds:
  world:
    ==: MVWorld
    hidden: 'false'
    alias: world
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -237.5
      y: 64.0
      z: 254.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '1'
    generator: ParadiseLand
    playerLimit: '-1'
    allowFlight: 'true'
```

In your generator property is missed the "eden.yml" ID.
So if I replace it with "generator: ParadiseLand:eden.yml", it does work =)

**Comment by benwoo1110** [comment]
MV5 has improved first spawn world handling. Open a new issue if you are still facing any problem with it.
