### ISSUE TITLE
Error when using b:playerbed

### ISSUE THREAD

**Issue by bobland1** [Multiverse/Multiverse-Core#2265]
```
[13:18:38] [Server thread/INFO]: HairyNinja118 issued server command: /mvtp b:playerbed
[13:19:42] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: 0
	at pl.plajer.buildbattle.utils.ExceptionLogHandler.publish(ExceptionLogHandler.java:74) ~[?:?]
	at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_231]
	at java.util.logging.Logger.doLog(Unknown Source) ~[?:1.8.0_231]
	at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:544) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:986) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```
As well as the error, the b:playerbed doesn't teleport either. It says the bed is invalid

**Comment by bobland1** [comment]
Am I using b:playerBed wrong?
