### ISSUE TITLE
World Regeneration Fails When Run From Console Using Paper #263+

### ISSUE THREAD

**Issue by StirFryBeans** [Multiverse/Multiverse-Core#2268]
**Expected Behavior**
When running the command `/mvregen worldname` from the console, or more than once by a player, the world is expected to regenerate.
 
**Observed Behavior**
When running the command `/mvregen worldname` from the console, or more than once by a player, the regeneration fails and gives the below exception in the console.
<details>
  <summary>Console Output</summary>

  ```
  > mvregen world_nether
[21:06:21 INFO]: The command mvregen has been halted due to the fact that it could break something!
[21:06:21 INFO]: If you still wish to execute mvregen
[21:06:21 INFO]: please type: /mvconfirm
[21:06:21 INFO]: /mvconfirm will only be available for 10 seconds.
> mvconfirm
[21:06:22 INFO]: [Multiverse-Core] World 'world_nether' was unloaded from memory.
[21:06:22 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:06:22 INFO]: [Multiverse-Core] World 'world_nether' was unloaded from memory.
[21:06:23 INFO]: [Multiverse-Core] World 'world_nether' was DELETED.
[21:06:23 WARN]: java.lang.NullPointerException
[21:06:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createWorld(CraftServer.java:1039)
[21:06:23 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:548)
[21:06:23 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:320)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.regenWorld(WorldManager.java:882)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.regenWorld(MultiverseCore.java:1199)
[21:06:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:06:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:06:23 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:06:23 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[21:06:23 WARN]:        at com.onarandombox.commandhandler.QueuedCommand.execute(QueuedCommand.java:49)
[21:06:23 WARN]:        at com.onarandombox.commandhandler.CommandHandler.confirmQueuedCommand(CommandHandler.java:218)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.commands.ConfirmCommand.runCommand(ConfirmCommand.java:36)
[21:06:23 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[21:06:23 WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[21:06:23 WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[21:06:23 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:912)
[21:06:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:06:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:06:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[21:06:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723)
[21:06:23 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[21:06:23 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[21:06:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169)
[21:06:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958)
[21:06:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:06:23 ERROR]: [Multiverse-Core] The world 'world_nether' could NOT be loaded because it contains errors and is probably corrupt!
[21:06:23 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'world_nether'
[21:06:23 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[21:06:23 INFO]: World could NOT be regenerated!
  ```
</details>

**Steps to replicate:**

1. Download and run [Paper build #263](https://papermc.io/ci/job/Paper-1.15/263/) or newer
2. Install latest version [Multiverse Core version 4.1.1](https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-4.1.1-SNAPSHOT.jar) as normal, default configuration for everything is fine.
3. Attempt to regenerate any world through the console by using `/mvregen world` and `/mvconfirm` or do the previous twice as a player on the server.
4. The command will fail through the console on the first try, or on the second try in game, with the above output.

**Comment by StirFryBeans** [comment]
This is the commit between Paper #262 and #263, https://github.com/PaperMC/Paper/commit/a71a4ec21544217cdb82f10a54647fc4a873c0a5

**Comment by nicegamer7** [comment]
I just confirmed this. I spoke with some of the Paper guys, and it seems that this only happens with the main worlds (i.e. the world specified in `server.properties` and it's nether/end worlds).

**Comment by nicegamer7** [comment]
Fixed in Paper Build 319. See https://github.com/PaperMC/Paper/commit/b88ee11f5ad35a63e5e28bf2748c89a4f0a6ec91. Thanks for reporting :)
