### ISSUE TITLE
Exception while loading value for environment

### ISSUE THREAD

**Issue by iornminer** [Multiverse/Multiverse-Core#2269]
Hello! I have no idea why but multiverse-core isn't working (it's showing up in /plugins but is red)
From console, this is what it says:
[20:09:25] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.1.0-b775
[20:09:25] [Server thread/WARN]: [Multiverse-Core] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.
[20:09:25] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].
[20:09:25] [Server thread/INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do. The performance impact is negligible.
[20:09:25] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment

[20:09:25] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot set to an empty path
at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:188) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:222) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:79) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:77) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:67) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-214]
at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorldConfig(WorldManager.java:775) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:504) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[20:09:25] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775
[20:09:25] [Server thread/ERROR]: Error occurred while disabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
i have attached a picture of the rest, please help, thanks!
![MineHost pl __ Konsola - Google Chrome 27_05_2020 19_16_44 (2)](https://user-images.githubusercontent.com/66031923/83057496-dfbfbe80-a04e-11ea-8a1d-2d2f24adeef8.png)

**Comment by benwoo1110** [comment]
Try removing all plugins other than mv to test.

**Comment by nicegamer7** [comment]
In #2344, the user mentions that MV is the only plugin installed. Another user on Discord is experiencing this issue after updating to 1.16.2.

**Comment by benwoo1110** [comment]
Is anyone still facing this issue on the latest version of mv and papermc 1.16.4?

**Comment by benwoo1110** [comment]
likely a server software issue, can reproduce in latest versions of mc
