### ISSUE TITLE
Dimension , does not exist 

### ISSUE THREAD

**Issue by Untek** [Multiverse/Multiverse-Core#2283]
Hello

I have a problem an error message when I leave my main map and I am disconnected on a map other than the main one this error appears do you have any solutions?

[17:10:10] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302) ~[DimensionManager.class:?]
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:65) ~[bjf.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:871) ~[bjb.class:?]
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32) ~[hs.class:?]
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13) ~[hs.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by benwoo1110** [comment]
Bukkit + Forge hack servers always tent to have bugs that cause these issues. Also 1.7.10 is very old and long unsupported by MV.
