### ISSUE TITLE
I can't create a new World

### ISSUE THREAD

**Issue by Lreine** [Multiverse/Multiverse-Core#2335]
I can't create a new world, this is the bug in the console:

[13:59:24 INFO]: Lreine issued server command: /mv create Spawn normal -t flat
[13:59:24 WARN]: java.lang.NullPointerException
[13:59:24 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:898)
[13:59:24 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:59:24 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:59:24 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:59:24 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:59:24 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:59:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:59:24 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by nicegamer7** [comment]
Which version of MV are you using?

**Comment by benwoo1110** [comment]
For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by benwoo1110** [comment]
The version of MV I linked above should solve your issue, I will close it for now. If you still face any issue, feel free to reopen the issue or come to our MV discord https://discord.gg/NZtfKky
