### ISSUE TITLE
Unable to clone worlds..

### ISSUE THREAD

**Issue by mikey1665** [Multiverse/Multiverse-Core#2337]
I keep getting this error when I try to clone any kind of world.

`[18:56:26] [Server thread/INFO]: [Multiverse-Core] Copying files for world 'world'
[18:56:26] [Server thread/WARN]: [Multiverse-Core] Unable to copy directory
java.nio.file.FileSystemException: .\world\session.lock -> .\world2\session.lock: The process cannot access the file because another process has locked a portion of the file.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source) ~[?:1.8.0_251]
	at java.nio.file.Files.copy(Unknown Source) ~[?:1.8.0_251]
	at com.onarandombox.MultiverseCore.utils.FileUtils$CopyDirFileVisitor.visitFile(FileUtils.java:112) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.FileUtils$CopyDirFileVisitor.visitFile(FileUtils.java:90) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:1.8.0_251]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:1.8.0_251]
	at com.onarandombox.MultiverseCore.utils.FileUtils.copyFolder(FileUtils.java:82) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.cloneWorld(WorldManager.java:180) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CloneCommand.runCommand(CloneCommand.java:49) ~[?:?]
	at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296) ~[?:?]
	at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:820) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[18:56:26] [Server thread/WARN]: [Multiverse-Core] Failed to copy files for world 'world2', see the log info`

**Comment by benwoo1110** [comment]
One workaround I found is to do `/mv import <clone_worldname> <type>` after cloning. But it is definitely a bug and we will be looking into it.
