### ISSUE TITLE
error while importing worlds

### ISSUE THREAD

**Issue by Drafothedragon** [Multiverse/Multiverse-Core#2340]
i want to import a world but it allways not working.

The console prints this to me: 

> [22:30:04 WARN]: Could not set level chunk heightmap, array length is 0 instead of 256
> [22:30:04 ERROR]: Could not pass event WorldLoadEvent to Multiverse-Core v4.1.0-b775
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:949) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.Bukkit.createWorld(Bukkit.java:454) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [server.jar:git-Spigot-dcd1643-e60fc34]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:269) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:165) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-4.1.0.jar:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:910) [Multiverse-Core-4.1.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
at net.minecraft.server.v1_12_R1.NibbleArray.<init>(NibbleArray.java:14) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:402) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:94) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:72) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:138) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:568) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:84) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:423) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:82) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:477) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:404) ~[?:?]
at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 29 more

**Comment by nicegamer7** [comment]
For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by Drafothedragon** [comment]
Okay i will try it some time later, but thank you ^^ 

> For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by benwoo1110** [comment]
That version nicegamer7 link should work. You also need to ensure the world you need to import is of the same mc version as your server. If you still have issues, you can reopen this or ask in our discord  https://discord.gg/NZtfKky
