### ISSUE TITLE
Multiverse-Core error while loading Plotsquared World in 1.16

### ISSUE THREAD

**Issue by PapiCapi** [Multiverse/Multiverse-Core#2346]
Hello, when i'm using the latest version of WorldEdit i got an arror when Multiverse loads the Plotsquared world : 

```
[14:52:07] [Server thread/INFO]: -------- World Settings For [creaplots113] --------
[14:52:07] [Server thread/INFO]: Experience Merge Radius: 6.0
[14:52:07] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Carrot Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Potato Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Kelp Growth Modifier: 100%
[14:52:07] [Server thread/INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 1 / Tiv true
[14:52:07] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[14:52:07] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[14:52:07] [Server thread/INFO]: Max TNT Explosions: 100
[14:52:07] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:52:07] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:52:07] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[14:52:07] [Server thread/INFO]: Item Merge Radius: 4.0
[14:52:07] [Server thread/INFO]: Item Despawn Rate: 3000
[14:52:07] [Server thread/INFO]: View Distance: 3
[14:52:07] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[14:52:07] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:52:07] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:52:07] [Server thread/INFO]: Mob Spawn Range: 6
[14:52:07] [Server thread/INFO]: [Moncube] Detected world load for 'creaplots113'
[14:52:07] [Server thread/INFO]: [Moncube]  - generator: PlotSquared>PlotSquared
[14:52:07] [Server thread/INFO]: [Moncube]  - plotworld: com.plotsquared.core.generator.HybridPlotWorld
[14:52:07] [Server thread/INFO]: [Moncube]  - plotAreaManager: com.plotsquared.core.generator.HybridPlotManager
[14:52:07] [Server thread/INFO]: [Moncube]  - default flags:  pve:true
[14:52:07] [Server thread/INFO]: [Moncube]  - road flags:  pve:true
[14:52:07] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.__f4e8f6400ef849498f9d5609a3613a06__getBiome(Lcom/sk89q/worldedit/math/BlockVector2;)Lcom/sk89q/worldedit/world/biome/BiomeType;
	at com.sk89q.worldedit.extent.clipboard.InjectableClipboard.getBiome(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.getBiome(BlockArrayClipboard.java) ~[?:?]
	at com.plotsquared.core.generator.HybridPlotWorld.setupSchematics(HybridPlotWorld.java:316) ~[?:?]
	at com.plotsquared.core.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:160) ~[?:?]
	at com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:410) ~[?:?]
	at com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:1169) ~[?:?]
	at com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:110) ~[?:?]
	at net.minecraft.server.v1_16_R1.MinecraftServer.initWorld(MinecraftServer.java:485) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createWorld(CraftServer.java:1154) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:570) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:320) ~[patched_1.16.1.jar:git-Paper-79]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-79]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14:52:07] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775
```

However this error is thrown when using WorldEdit 7.2.0 beta 2 BUT when i'm using WorldEdit 7.1.1 ( which is a snapshot ) i don't have any errors.

Plugins : Multiverse-Core 4.1.0 , Plotsquared 5.12.4 (premium) and WorldEdit 7.2.0 beta 2

**Comment by leviem1** [comment]
I think the issue is caused by WorldEdit, not Multiverse.

The error message explains that Multiverse started PlotSquared correctly, but there was an error when PlotSquared was running the WorldEdit code. This is likely due to the fact that you're using a WorldEdit Beta, which means that it's still in testing and still has bugs.

You should report this to WorldEdit though if someone hasn't already! 😄

**Comment by PapiCapi** [comment]
I tried with another world management plugin but didn't get the error and the world loaded succesfully so for me, this is really coming from Multiverse

**Comment by leviem1** [comment]
I don't know what the other world management plugin is doing, but the error you have above describes an incompatibility between PlotSquared and the latest WorldEdit beta. This makes sense by process of elimination since WorldEdit is the only thing you said you changed, correct?

Here's my technical explanation: PlotSquared runs `blockArrayClipboard1.getBiome(BlockVector2)` [here](https://github.com/IntellectualSites/PlotSquared/blob/57435fdf349a9af989b13f9ddd70b0466370f25a/Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java#L316). The method `getBiome(BlockVector2)` doesn't exist in the latest WorldEdit as it's been changed to `getBiome(BlockVector3)` in [this](https://github.com/EngineHub/WorldEdit/commit/f5e36ed8a8abcf1247bb874399de676c35f3d538#diff-f216d1b57f0fd9b54324cf837e935499R169) update. This breaks backwards compatibility, which WorldEdit should _probably_ do something about (and I think they plan to), but ultimately it's PlotSquared's job to keep up with WorldEdit if they don't.

Try testing with a stable version of [AWE](https://www.spigotmc.org/resources/asyncworldedit.327/) or [FAWE](https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/) instead of your current WorldEdit real quick. That's what I use. I have no errors, and it's absurdly faster. If it works, then the cause should be clear.

After spending the last hour investigating this, I've think I've proven that I was incorrect in my earlier advice. This is technically a **PlotSquared** bug, not a WorldEdit _or_ Multiverse bug.

**Comment by PapiCapi** [comment]
Seems to be fixed in the latest plotsquared build, yeah.
Thanks :)

**Comment by nicegamer7** [comment]
Nice!
