### ISSUE TITLE
Unable to load world, "Exception while loading value for environment"

### ISSUE THREAD

**Issue by reelpufferfish** [Multiverse/Multiverse-Core#2390]
Here's a snippet of the console log:
```
> [02:38:34 WARN]: [Multiverse-Core] Exception while loading value for environment
> [02:38:34 WARN]: [Multiverse-Core] Exception while loading value for environment
> [02:38:34 WARN]: java.lang.NullPointerException
> [02:38:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createWorld(CraftServer.java:1074)
> [02:38:34 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:570)
> [02:38:34 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325)
> [02:38:34 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
> [02:38:34 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
> [02:38:34 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
> [02:38:34 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
> [02:38:34 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
> [02:38:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [02:38:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
> [02:38:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
> [02:38:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
> [02:38:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
> [02:38:34 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
> [02:38:34 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
> [02:38:34 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941)
> [02:38:34 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
> [02:38:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
> [02:38:34 ERROR]: [Multiverse-Core] The world 'Classic' could NOT be loaded because it contains errors and is probably corrupt!
> [02:38:34 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Classic'
> [02:38:34 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
```
The world is working just fine in 1.16 vanilla Minecraft, and I've run Minecraft Region fixer and it found no corrupted chunks or files. This is a rather large world, around 375mb.

**Comment by reelpufferfish** [comment]
My mistake, not an issue with MV.
