### ISSUE TITLE
Is it up to date ? issue

### ISSUE THREAD

**Issue by Hissam1048v** [Multiverse/Multiverse-Core#2408]
>.... [08:47:47 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.1.0-b775
>.... [08:47:47 WARN]: [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].
>.... [08:47:47 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do. The performance impact is negligible.
>.... [08:47:47 WARN]: [Multiverse-Core] Cannot load worlds.yml
>.... [08:47:47 INFO]: [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: NORMAL & seed: 2313422661961580709
>.... [08:47:47 INFO]: [Multiverse-Core] Loading World & Settings - 'world_nether' - Env: NETHER - Type: NORMAL & seed: 2313422661961580709
>.... [08:47:47 INFO]: [Multiverse-Core] Loading World & Settings - 'world_the_end' - Env: THE_END - Type: NORMAL & seed: 2313422661961580709
>.... [08:47:47 INFO]: [Multiverse-Core] 3 - World(s) loaded.
>.... [08:47:47 ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:351) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-387]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-387]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-387]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
>.... [08:47:47 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775

How do I fix it ? I am on 1.15.2 PaperMC. Sry for not following the format

**Comment by NeverGrowUp** [comment]
I would update your MV-core in the first instance.
https://ci.onarandombox.com/job/Multiverse-Core/
Build 789 is safe to use on 1.13+

**Comment by benwoo1110** [comment]
see https://github.com/Multiverse/Multiverse-Core/issues/2215#issuecomment-640545807
