### ISSUE TITLE
Error occurred while enabling Multiverse-*

### ISSUE THREAD

**Issue by joex92** [Multiverse/Multiverse-Core#2499]
ok, I was using all the multiverse plugins fine in 1.16.3...
now that I updated to 1.16.4, I get this warn:
```apache
[02:28:12] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.3-SNAPSHOT-b818
[02:28:12] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.2.3-SNAPSHOT-b818" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[02:28:12] [Server thread/INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
```

But then, it starts loading the worlds, and after doing that I get this errors:
```apache
[02:29:52] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.2.3-SNAPSHOT-b818 (Is it up to date?)
java.lang.OutOfMemoryError: Java heap space
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.<init>(Long2ObjectOpenHashMap.java:107) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at gg.airplane.structs.ConcLong2ObjectOpenHashMap$LongBucket.<init>(ConcLong2ObjectOpenHashMap.java:27) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at gg.airplane.structs.ConcLong2ObjectOpenHashMap.<init>(ConcLong2ObjectOpenHashMap.java:121) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.<init>(ChunkProviderServer.java:52) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.WorldServer.<init>(WorldServer.java:341) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1160) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:581) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:499) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:480) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:455) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:767) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:307) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3067/893094384.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[02:29:52] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.2.3-SNAPSHOT-b818
[02:30:02] [Server thread/INFO]: [Multiverse-Inventories] Enabling Multiverse-Inventories v4.2.2-SNAPSHOT-b495
[02:30:32] [Server thread/ERROR]: Error occurred while enabling Multiverse-Inventories v4.2.2-SNAPSHOT-b495 (Is it up to date?)
java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore
	at com.onarandombox.multiverseinventories.MultiverseInventories.onEnable(MultiverseInventories.java:129) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 11 more
[02:30:32] [Server thread/INFO]: [Multiverse-Inventories] Disabling Multiverse-Inventories v4.2.2-SNAPSHOT-b495
[02:30:32] [Server thread/ERROR]: Error occurred while disabling Multiverse-Inventories v4.2.2-SNAPSHOT-b495 (Is it up to date?)
java.lang.NullPointerException: null
	at com.onarandombox.multiverseinventories.MultiverseInventories.onDisable(MultiverseInventories.java:115) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[02:30:36] [Server thread/INFO]: [Multiverse-SignPortals] Enabling Multiverse-SignPortals v4.2.1-SNAPSHOT-b765
[02:30:36] [Server thread/ERROR]: Error occurred while enabling Multiverse-SignPortals v4.2.1-SNAPSHOT-b765 (Is it up to date?)
java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore
	at com.onarandombox.MultiverseSignPortals.MultiverseSignPortals.onEnable(MultiverseSignPortals.java:36) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 11 more
[02:30:36] [Server thread/INFO]: [Multiverse-SignPortals] Disabling Multiverse-SignPortals v4.2.1-SNAPSHOT-b765
[02:30:36] [Server thread/INFO]: [Multiverse-SignPortals] - Disabled
[02:30:38] [Server thread/INFO]: [Multiverse-EssentialsSupport] Enabling Multiverse-EssentialsSupport v2.5-b3*
[02:30:42] [Server thread/ERROR]: Error occurred while enabling Multiverse-EssentialsSupport v2.5-b3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore
	at com.onarandombox.MultiverseEssentialsSupport.MultiverseCore.api.MultiversePlugin.onEnable(MultiversePlugin.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 11 more
[02:30:42] [Server thread/INFO]: [Multiverse-EssentialsSupport] Disabling Multiverse-EssentialsSupport v2.5-b3
```
And it bugs me a lot, because I tried ALL THE EXACT SAME PLUGINS AND SERVER locally in my computer and it worked fine with no problem, but suddenly when uploading the plugins and the server jar to the hosting, it doesn't work... Am I doing something wrong? am I missing something? is it the RAM size?

**Comment by benwoo1110** [comment]
```ava.lang.OutOfMemoryError: Java heap space```

This just your server ran out of memory, probably due to poor spec or loading too many world/plugins. Since you are using a hosting company, either get one with more ram and better performance. Or change a hosting company.

for the first warning, see #2000

**Comment by joex92** [comment]
oh ok thanks... I though It was maybe another thing... thanks...
