### ISSUE TITLE
Errot spigot version 1.12

### ISSUE THREAD

**Issue by phuongtruong004** [Multiverse/Multiverse-Core#2540]
[13:41:27 WARN]: java.lang.NullPointerException
[13:41:27 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[13:41:27 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:41:27 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:41:27 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:41:27 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:41:27 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[13:41:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[13:41:27 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by benwoo1110** [comment]
MC 1.12 You will need to use an older version of Multiverse - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161
