### ISSUE TITLE
I use version MultiverseCore 2.5.0

### ISSUE THREAD

**Issue by phuongtruong004** [Multiverse/Multiverse-Core#2541]
[14:16:14 WARN]: java.lang.NullPointerException
[14:16:14 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[14:16:14 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:16:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:16:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[14:16:14 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:16:14 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[14:16:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[14:16:14 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by benwoo1110** [comment]
Even so, please at least fill in the issue template.

https://github.com/Multiverse/Multiverse-Core/issues/new?assignees=&labels=Type%3A+Assistance&template=help.md&title=
