### ISSUE TITLE
Rip my server, Multiverse crashed somehow

### ISSUE THREAD

**Issue by pjindras** [Multiverse/Multiverse-Core#2595]
[22:05:24] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.3-SNAPSHOT-b821
[22:05:24] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.2.3-SNAPSHOT-b821" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[22:05:24] [Server thread/INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[22:05:24] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.2.3-SNAPSHOT-b821 (Is it up to date?)
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: Pripravujeme
     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:50) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:143) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.WorldCreator.<init>(WorldCreator.java:31) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.WorldCreator.name(WorldCreator.java:391) ~[patched_1.16.5.jar:git-Paper-540]
     at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:463) ~[?:?]
     at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:455) ~[?:?]
     at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:767) ~[?:?]
     at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:307) ~[?:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-540]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
[22:05:24] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.2.3-SNAPSHOT-b821
[22:05:24] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.27-SNAPSHOT (build 2276)
[22:05:24] [Server thread/WARN]: [NexEngine] Loaded class net.citizensnpcs.api.trait.TraitInfo from Citizens v2.0.27-SNAPSHOT (build 2276) which is not a depend, softdepend or loadbefore of this plugin.
[22:05:24] [Server thread/INFO]: [NexEngine] [Hook] Citizens: Success!
[22:05:24] [Server thread/INFO]: [StayPut] Enabling StayPut v1.2.1
[22:05:24] [Server thread/ERROR]: Error occurred while enabling StayPut v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore
     at nl.zandervdm.stayput.Utils.MVManager.<init>(MVManager.java:12) ~[?:?]
     at nl.zandervdm.stayput.Main.setupClasses(Main.java:99) ~[?:?]
     at nl.zandervdm.stayput.Main.onEnable(Main.java:58) ~[?:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Paper-540]
     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-540]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore
     at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_261]
     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-540]
     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-540]
     at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_261]
     at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]

### Information

* **Server version:**1.16.5

* **Full output of `/mv version -p`:** v4.2.3-SNAPSHOT-b821

### Help request

Multiverse is not working anymore after server restart, could you help me please?

Thank you

**Comment by nicegamer7** [comment]
Looks like the server is complaining about a world named `Pripravujeme` because of the capital letter. Did you make this world with MV? Or did you import it?

**Comment by benwoo1110** [comment]
https://github.com/PaperMC/Paper/issues/5331 Was an issue with paper and having faulty logic for invalid world name validation.
