### ISSUE TITLE
IllegalStateExceptions on server 1.17 start-up

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#2640]
### Information

* **Server version:**
```
>version
[08:46:44] [Server thread/INFO]: This server is running CraftBukkit version 3133-Spigot-66f9d3c-3fa79d3 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[08:46:44] [Server thread/INFO]: You are running the latest version
```

* **Full output of `/mv version -p`:** 
```
>mv version -p
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Multiverse-Core Version: 4.2.3-SNAPSHOT-b845
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Bukkit Version: 3133-Spigot-66f9d3c-3fa79d3 (MC: 1.17)
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@150322162":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_yellowdog"}}, {"MVWorld@1483542211":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_blackdog_the_end"}}, {"MVWorld@726848529":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_blackdog_nether"}}, {"MVWorld@1902218027":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_whitedog"}}, {"MVWorld@485184145":{"Gen":"BentoBox","Type":"NORMAL","Env":"THE_END","Name":"world_skyblock_the_end"}}, {"MVWorld@742415577":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_westeros"}}, {"MVWorld@286254876":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_whitedog_nether"}}, {"MVWorld@1816792773":{"Gen":"VoidGenerator","Type":"NORMAL","Env":"NORMAL","Name":"world_void"}}, {"MVWorld@712222215":{"Gen":"BentoBox","Type":"NORMAL","Env":"NETHER","Name":"world_skyblock_nether"}}, {"MVWorld@75206916":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_luckyblock"}}, {"MVWorld@1780658576":{"Gen":"BentoBox","Type":"NORMAL","Env":"NORMAL","Name":"world_skyblock"}}, {"MVWorld@1445115447":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1641443690":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@964509669":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@1177331563":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_yellowdog_nether"}}, {"MVWorld@2074901399":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_lobby"}}, {"MVWorld@92021399":{"Gen":"CityWorld","Type":"NORMAL","Env":"NORMAL","Name":"world_city"}}, {"MVWorld@1475567219":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_blackdog"}}]
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 3
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Economy being used: Simple Item Economy
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9)
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   enforceaccess: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   prefixchat: false
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat%
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   useasyncchat: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   teleportintercept: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   firstspawnoverride: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   displaypermerrors: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   enablebuscript: false
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   globaldebug: 0
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   silentstart: false
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   messagecooldown: 5000
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   version: 2.9
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   firstspawnworld: world_lobby
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   teleportcooldown: 1000
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   defaultportalsearch: false
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   portalsearchradius: 128
[08:45:53] [Server thread/INFO]: [Multiverse-Core]   autopurge: true
[08:45:53] [Server thread/INFO]: [Multiverse-Core] Special Code: FRN002
[08:45:53] [Server thread/INFO]: [Multiverse-Portals] Multiverse-Portals Version: 4.2.2-SNAPSHOT-b846
[08:45:53] [Server thread/INFO]: [Multiverse-Portals] Loaded Portals: 8
[08:45:53] [Server thread/INFO]: [Multiverse-Portals] Dumping Portal Values: (version 2.7)
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   wand: 271
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   useonmove: true
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   portalsdefaulttonether: false
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   enforceportalaccess: false
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   portalcooldown: 1000
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   clearonremove: false
[08:45:53] [Server thread/INFO]: [Multiverse-Portals]   framematerials: []
[08:45:53] [Server thread/INFO]: [Multiverse-Portals] Special Code: FRN001
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Multiverse-Inventories Version: 4.2.3-SNAPSHOT-b512
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] === Settings ===
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] First Run: false
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Using Bypass: false
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Default Ungrouped Worlds: false
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Save and Load on Log In and Out: false
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Using GameMode Profiles: false
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] === Shares ===
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Optionals for Ungrouped Worlds: true
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] Enabled Optionals: 
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] === Groups ===
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] blackdog: {Worlds: [world_blackdog_nether, world_blackdog_the_end, world_blackdog], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] city: {Worlds: [world_city_the_end, world_city, world_city_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] creative: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] lobby: {Worlds: [world_lobby], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] luckyblock: {Worlds: [world_luckyblock], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] mini: {Worlds: [world_minigames], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] skyblock: {Worlds: [world_skyblock, world_skyblock_the_end, world_skyblock_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] void: {Worlds: [world_void], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] westeros: {Worlds: [world_westeros], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] whitedog: {Worlds: [world_whitedog_the_end, world_whitedog, world_whitedog_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-Inventories] yellowdog: {Worlds: [world_yellowdog_the_end, world_yellowdog, world_yellowdog_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Multiverse-NetherPortals Version: 4.2.2-SNAPSHOT-b801
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Nether Prefix: 
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Nether Suffix: _nether
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] End Prefix: 
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] End Suffix: _the_end
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Nether Links: {}
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] End Links: {}
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Bounceback: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Teleport Entities: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Send Disabled Portal Message: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Send No Destination Message: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Server Allow Nether: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Server Allow End: true
[08:45:53] [Server thread/INFO]: [Multiverse-NetherPortals] Special Code: FRN001
[08:45:53] [Craft Scheduler Thread - 0/INFO]: [Multiverse-Core] Version info dumped here: https://j.mp/3ghTOSk
```

* **Server log:** 
contains many instances of the following, in many different worlds:
```
[08:31:13] [Server thread/INFO]: Preparing start region for dimension minecraft:world_blackdog
[08:31:13] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[08:31:14] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[08:31:14] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
        at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1082) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
See above.

**Steps to reproduce**  
- Update Spigot from 1.16.5-3096 to Spigot 1.17-3133
- Start server with --forceUpgrade and --eraseCache
- Wait for worlds to rebuild
- Stop server
- Start server
- Review logs/latest.log for errors

**Expected behavior**  

**Screenshots**

**Comment by benwoo1110** [comment]
hmm high chance it's a bug with a spigot, will need to investigate more. Does it occur on a fresh 1.17 installed? i.e. not upgrading from 1.16.5 or below.

**Comment by nicegamer7** [comment]
Not a Multiverse bug, I'm almost certain. @SlimeDog I suggest you check Spigot's JIRA to see if this has been reported before.

**Comment by SlimeDog** [comment]
> Does it occur on a fresh 1.17 installed? i.e. not upgrading from 1.16.5 or below.

Don't know. I need to test too many plugins with my worlds intact. When I get some free cycles, I try a fresh install. You (or someone else) may get there first.

**Comment by nicegamer7** [comment]
I just checked and there's no report of this on Spigot's JIRA or on their Discord. Does your world `world_blackdog` have structures on or off?

**Comment by SlimeDog** [comment]
> Does your world `world_blackdog` have structures on or off?

I believe all worlds have structures on. What specific setting do you want me to report?

**Comment by nicegamer7** [comment]
I don't think the structures setting is saved anywhere, it's just a flag provided when making the world.

**Comment by SlimeDog** [comment]
Then structures are on, in all worlds.

I removed the region and poi files, and restarted. No MV errors. It looks like Spigot or MC is failing on PillagerOutposts
```
[10:18:10] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[10:18:10] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
        at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:802) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:603) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17-3133.jar:3133-Spigot-66f9d3c-3fa79d3]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by nicegamer7** [comment]
I got confirmation from Choco on Spigot's Discord that this is not an MV bug, closing as such.
