### ISSUE TITLE
Issue with world since 1.17 - also an error in console

### ISSUE THREAD

**Issue by CloudeLecaw** [Multiverse/Multiverse-Core#2643]
Well it might not be so interesting because we create a new farmworld not for the 1.17
but still would be nice to know what throws this error in loading of the current one

```
23:53:10] [Server thread/INFO]: Preparing start region for dimension minecraft:farmwelt
[23:53:10] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[23:53:10] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[23:53:11] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[23:53:11] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[23:53:11] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
	at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1081) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:53:11] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[23:53:11] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
	at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1081) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:53:11] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[23:53:11] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
	at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1081) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:53:11] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[23:53:11] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
	at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1081) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:53:11] [Server thread/ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[23:53:11] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
	at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(SourceFile:39) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(SourceFile:57) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:505) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:216) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.PlayerChunkMap.lambda$20(PlayerChunkMap.java:561) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:603) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:614) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:322) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1134) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1095) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:774) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1081) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:533) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:53:11] [Worker-Main-5/INFO]: Preparing spawn area: 1%
[23:53:12] [Worker-Main-4/INFO]: Preparing spawn area: 10%
[23:53:12] [Worker-Main-6/INFO]: Preparing spawn area: 20%
[23:53:13] [Worker-Main-5/INFO]: Preparing spawn area: 20%
[23:53:13] [Worker-Main-6/INFO]: Preparing spawn area: 33%
[23:53:14] [Worker-Main-4/INFO]: Preparing spawn area: 60%
[23:53:14] [Worker-Main-6/INFO]: Preparing spawn area: 92%
[23:53:14] [Server thread/INFO]: Time elapsed: 4647 ms
```

**Comment by benwoo1110** [comment]
#2640
