### ISSUE TITLE
[Bug]: Maps cannot be loaded

### ISSUE THREAD

**Issue by cribegit** [Multiverse/Multiverse-Core#2742]
### `/mv version -p` output

4.3.1

### Server logs

Server Error can be found in description

### Server Version

```shell
git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Bug Description

[18:52:25 WARN]: java.lang.RuntimeException: net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/CityBuild/./SpawnMap/session.lock: already locked (possibly by other Minecraft instance?) [18:52:25 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1126) [18:52:25 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:596) [18:52:25 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:380) [18:52:25 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486) [18:52:25 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288) [18:52:25 WARN]:        at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:131) [18:52:25 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296) [18:52:25 WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) [18:52:25 WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [18:52:25 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839) [18:52:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [18:52:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) [18:52:25 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) [18:52:25 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) [18:52:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831) [18:52:25 WARN]: Caused by: net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict: /home/CityBuild/./SpawnMap/session.lock: already locked (possibly by other Minecraft instance?) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.SessionLock$ExceptionWorldConflict.a(SourceFile:98) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.SessionLock.a(SourceFile:44) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.<init>(Convertable.java:257) [18:52:25 WARN]:        at net.minecraft.server.v1_16_R3.Convertable.c(Convertable.java:227) [18:52:25 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1124) [18:52:25 WARN]:        ... 19 more [18:52:25 ERROR]: [Multiverse-Core] The world 'SpawnMap' could NOT be loaded because it contains errors and is probably corrupt! [18:52:25 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'SpawnMap' [18:52:25 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer [18:52:25 ERROR]: [Multiverse-Core] Failed to Create/Load the world 'SpawnMap'

- Any Map installed on my Server cannot be loaded cause of this error, reloading the system, reimporting the map etc. were not giving any success.

I would be happy if someone could help me

### Steps to reproduce

I havent found any way to fix that bug D:

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Delete the `session.lock` file for SpawnMap world and try again.
