### ISSUE TITLE
[Bug]: Cannot Running

### ISSUE THREAD

**Issue by Hututu316** [Multiverse/Multiverse-Core#2777]
### `/mv version -p` output

Multiverse-Core v4.3.1-b861

### Server logs

[20:16:49] [Server thread/INFO] [com.onarandombox.MultiverseCore.MultiverseCore/]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861 [20:16:49] [Server thread/WARN] [com.onarandombox.MultiverseCore.MultiverseCore/]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--]. [20:16:49] [Server thread/INFO] [Minecraft/]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore. [20:16:51] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Multiverse-Core v4.3.1-b861 (Is it up to date?) java.lang.NullPointerException: Cannot invoke "net.minecraft.world.storage.ServerWorldInfo.func_230409_a_(net.minecraft.world.Difficulty)" because "org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getHandle().worldDataServer" is null 	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.setDifficulty(CraftWorld.java:1275) ~[forge:7e29f765-296df566-9fb885e8] 	at com.onarandombox.MultiverseCore.MVWorld$2.set(MVWorld.java:120) ~[?:?] 	at com.onarandombox.MultiverseCore.MVWorld$2.set(MVWorld.java:115) ~[?:?] 	at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.flushPendingVPropChanges(SerializationConfig.java:248) ~[?:?] 	at com.onarandombox.MultiverseCore.WorldProperties.flushChanges(WorldProperties.java:376) ~[?:?] 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:92) ~[?:?] 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?] 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:496) ~[?:?] 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?] 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?] 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?] 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8] 	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429) ~[?:?] 	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:772) ~[?:?] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] 	at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Server Version

```shell
mohist 1.16.5
```

### Bug Description

[20:16:49] [Server thread/INFO] [com.onarandombox.MultiverseCore.MultiverseCore/]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
[20:16:49] [Server thread/WARN] [com.onarandombox.MultiverseCore.MultiverseCore/]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[20:16:49] [Server thread/INFO] [Minecraft/]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[20:16:51] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Multiverse-Core v4.3.1-b861 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.storage.ServerWorldInfo.func_230409_a_(net.minecraft.world.Difficulty)" because "org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getHandle().worldDataServer" is null
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.setDifficulty(CraftWorld.java:1275) ~[forge:7e29f765-296df566-9fb885e8]
	at com.onarandombox.MultiverseCore.MVWorld$2.set(MVWorld.java:120) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld$2.set(MVWorld.java:115) ~[?:?]
	at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.flushPendingVPropChanges(SerializationConfig.java:248) ~[?:?]
	at com.onarandombox.MultiverseCore.WorldProperties.flushChanges(WorldProperties.java:376) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:92) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:496) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:772) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Steps to reproduce

When start server the plugin cannot work.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Could you give the `/mvv -p` link and full logs (see below how to do this)

<details>
  <summary>How to send the logs</summary>

The logs are found in `/logs/latest.log`. After you open that file you will see a lot of text, copy and paste that with CTRL+C and CTRL+V in to https://mclo.gs/ , just click save and send the link to the page it sends you to.
</details>

**Comment by Hututu316** [comment]
> 

here my link sir.https://mclo.gs/i6VgBjK

**Comment by zax71** [comment]
Multiverse doesn’t support Mohist or any other bukkit on forge software
