### ISSUE TITLE
[Bug]: NPE when using the placeholder %multiverse_world_alias%

### ISSUE THREAD

**Issue by ClayCoffee** [Multiverse/Multiverse-Core#2784]
### `/mv version -p` output

https://paste.gg/dc848e5f5950419694ecbca926beb648

### Server logs

-

### Server Version

```shell
This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)
```

### Bug Description

java.lang.NullPointerException: Cannot invoke "com.onarandombox.MultiverseCore.MultiverseCore.getMVWorldManager()" because "this.core" is null
        at com.extendedclip.papi.expansion.multiverse.MultiverseExpansion.onPlaceholderRequest(MultiverseExpansion.java:51) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:16) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.format.part.json.Text.process(Text.kt:25) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.format.part.json.Text.process$default(Text.kt:21) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:27) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:26) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:26) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:137) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:116) ~[TrChat-2.0.0-PRE-19.jar:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:64) ~[TrChat-2.0.0-PRE-19.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        ... 20 more

### Steps to reproduce

1. use the placeholder %multiverse_world_alias%
2. NPE

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
I cannot reproduce this issue with Paper version 336 on 1.19.3 using Multiverse and PlaceholderAPI, with or without the Multiverse expansion.
