### ISSUE TITLE
[Bug]: Multiverse doesn´t work in 1.18.2

### ISSUE THREAD

**Issue by Josepeihs** [Multiverse/Multiverse-Core#2785]
### `/mv version -p` output

[14:07:14] [WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.toString()" because the return value of "com.onarandombox.MultiverseCore.MVWorld.getEnvironment()" is null [14:07:14] [WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.toString(MVWorld.java:1212) [14:07:14] [WARN]: 	at java.base/java.lang.String.valueOf(String.java:4215) [14:07:14] [WARN]: 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173) [14:07:14] [WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$CollectionView.toString(ConcurrentHashMap.java:4526) [14:07:14] [WARN]: 	at java.base/java.lang.String.valueOf(String.java:4215) [14:07:14] [WARN]: 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173) [14:07:14] [WARN]: 	at com.onarandombox.MultiverseCore.commands.VersionCommand.getLegacyString(VersionCommand.java:58) [14:07:14] [WARN]: 	at com.onarandombox.MultiverseCore.commands.VersionCommand.addVersionInfoToEvent(VersionCommand.java:113) [14:07:14] [WARN]: 	at com.onarandombox.MultiverseCore.commands.VersionCommand.runCommand(VersionCommand.java:137) [14:07:14] [WARN]: 	at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296) [14:07:14] [WARN]: 	at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) [14:07:14] [WARN]: 	at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [14:07:14] [WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839) [14:07:14] [WARN]: 	at TRANSFORMER/forge@40.1.51/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [14:07:14] [WARN]: 	at TRANSFORMER/forge@40.1.51/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) [14:07:14] [WARN]: 	at TRANSFORMER/forge@40.1.51/org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:775) [14:07:14] [WARN]: 	at TRANSFORMER/forge@40.1.51/org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:761) [14:07:14] [WARN]: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:399) [14:07:14] [WARN]: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) [14:07:14] [WARN]: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:966) [14:07:14] [WARN]: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:789) [14:07:14] [WARN]: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286) [14:07:14] [WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833) [14:07:14] [INFO]: An internal error occurred when attempting to perform this command. [14:07:14] [INFO]: Details were printed to the server console and logs, please add that to your bug report.

### Server logs

https://mclo.gs/HnpEe7z

### Server Version

```shell
This server is running Mohist version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.51)
```

### Bug Description

Im trying install many versions of the plugins but it doesn´t work in 1.18.2. When i try create a world it says failed, the same thing that when I try to import a world. I cant see the version of the plugins with the command but the version I installed is 
Multiverse-Core-4.3.1.jar. Thanks for the help

### Steps to reproduce

1. Start a server in 1.18.2 with multiverse installed
2. Try to import o create a world
3. It failed all the times

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by willkroboth** [comment]
It looks like source of your problem is this error message:
```java
[Server thread/WARN] [/]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[Server thread/WARN] [/]: 	at TRANSFORMER/forge@40.1.51/org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:982)
```
I don't think this is a problem with Multiverse but, instead with the Mohist server you're using. I haven't used Mohist before, but this [PSA by EssentialsX](https://essentialsx.net/do-not-use-mohist.html) suggests that the way Mohist combines Bukkit and Forge often leads to errors like this. It looks like the code causing this problem is indeed in a modified version of the CraftServer class made by Mohist. When I tried this using a Spigot 1.18.2 server, Multiverse worked as intended, so I think you'll find a better solution by making a report on [Mohist's Github repository](https://github.com/MohistMC/Mohist/issues).

**Comment by Josepeihs** [comment]
Yes I know, Y tried it in only spigot versions and it works perfectly but the problem is when I try to put in it servers with plugins and mods. I tried mohist and magma in many versions but it didn't work. Do you know some software to put mods and plugins in 1.18.2 and multiverse works in it?

**Comment by Josepeihs** [comment]
Sorry I close it XD, so the problem is that. How can I get a server with plugins and mods in 1.18.2 and multiverse core works on it

**Comment by willkroboth** [comment]
Well, Mohist might be able to fix the problem on their side if you made a report on their project, so you would be able to use Multiverse with Mohist.

Looking for alternatives, it looks like [Magma](https://magmafoundation.org/) is pretty similar to Mohist, claiming to support both forge and spigot. Maybe their implementation works better and is compatible with Multiverse?

You could also find a Forge mod that has a similar function to Multiverse. It looks like [Multiworld](https://www.curseforge.com/minecraft/mc-mods/multiworld-mod) is a Forge and Paper mod with the basic functionality of Multiverse. While it doesn't have as many features, it might be good enough for what you want to do.

**Comment by Josepeihs** [comment]
Really thanks for the help
