### ISSUE TITLE
[Bug]: Can't enable plugin on Mohist 1.16.5

### ISSUE THREAD

**Issue by K85** [Multiverse/Multiverse-Core#2789]
### `/mv version -p` output

 [19:31:32 INFO]: This server is running Mohist version 1.16.5-1061 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39) > mv version -p [19:32:10 WARN]: Unexpected exception while parsing console command "mv version -p" org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.3.1-b861 - plugin is disabled.         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[forge:?]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:773) ~[forge:7e29f765-296df566-9fb885e8]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:757) ~[forge:7e29f765-296df566-9fb885e8]         at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:367) ~[?:?]         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:339) ~[?:?]         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003) ~[?:?]         at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?]         at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server logs

see below

### Server Version

```shell
Welcome to Mohist 1.16.5 ! - Mohist Developement Group - 1.16.5-1061, Java 61.0
> version
[19:31:32 INFO]: This server is running Mohist version 1.16.5-1061 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
```

### Bug Description

```
[19:26:12 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
[19:26:12 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[19:26:12 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[19:26:13 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: skylight_forest
[19:26:13 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[19:26:13 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: twilightforest
[19:26:13 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[19:26:13 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[19:26:13 ERROR]: Error occurred while enabling Multiverse-Core v4.3.1-b861 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
        at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:83) ~[?:?]
        at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
        at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:366) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:340) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:335) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[nashorn-core-compat-15.1.1.1.jar:?]
        ... 24 more
Caused by: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:976) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:329) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[nashorn-core-compat-15.1.1.1.jar:?]
        ... 24 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineAnonymousClass(java.lang.Class, byte[], java.lang.Object[])'
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:329) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[nashorn-core-compat-15.1.1.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[nashorn-core-compat-15.1.1.1.jar:?]
        ... 24 more

```

### Steps to reproduce

```
[19:30:47 INFO]: SakuraWald issued server command: /mv
[19:30:47 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.3.1-b861 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:773) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1833) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1668) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:939) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:922) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:902) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:822) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

```

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by nicegamer7** [comment]
You can try setting `enablebuscript` to `'false'` in the config, but if that doesn't work, there's nothing we can do. Mohist is not a supported platform.

**Comment by K85** [comment]
> You can try setting `enablebuscript` to `'false'` in the config, but if that doesn't work, there's nothing we can do. Mohist is not a supported platform.

This works.
