### ISSUE TITLE
[Bug]: Terra generator not working

### ISSUE THREAD

**Issue by callmeEthan** [Multiverse/Multiverse-Core#2811]
### `/mv version -p` output

https://paste.gg/p/anonymous/18b40b1e7f7a43599c521ba8bb502528

### Server logs

https://paste.gg/p/anonymous/d606e906475b40f39f03c3bb90d9bc20

### Server Version

```shell
[10:10:59 INFO]: fThis server is running Paper version git-Paper-220 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3dcfec4)r
aYou are running the latest versionr
7oPrevious version: git-Paper-215 (MC: 1.19.2)
```

### Bug Description

I tried a blank test server with only Multiverse (4.3.1) and Terra (6.2.0) installed but it not working.  
It's seem terra is properly loaded in the log but when I tried /mv gens I get an error:  
`
[10:10:50 INFO]: [Multiverse-Core] PLEASE IGNORE the 'Plugin X does not contain any generators' message below!
[10:10:50 WARN]: java.lang.IllegalArgumentException: No such config pack ""
[10:10:50 WARN]: 	at Terra.jar//com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$1(TerraBukkitPlugin.java:176)
[10:10:50 WARN]: 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[10:10:50 WARN]: 	at Terra.jar//com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$2(TerraBukkitPlugin.java:175)
[10:10:50 WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[10:10:50 WARN]: 	at Terra.jar//com.dfsek.terra.bukkit.TerraBukkitPlugin.getDefaultWorldGenerator(TerraBukkitPlugin.java:174)
[10:10:50 WARN]: 	at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.commands.GeneratorCommand.runCommand(GeneratorCommand.java:44)
[10:10:50 WARN]: 	at Multiverse-Core-4.3.1.jar//com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[10:10:50 WARN]: 	at Multiverse-Core-4.3.1.jar//com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[10:10:50 WARN]: 	at Multiverse-Core-4.3.1.jar//com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[10:10:50 WARN]: 	at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[10:10:50 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:10:50 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[10:10:50 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[10:10:50 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879)
[10:10:50 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:500)
[10:10:50 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[10:10:50 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:10:50 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[10:10:50 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[10:10:50 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:10:50 INFO]: cAn internal error occurred when attempting to perform this command.
[10:10:50 INFO]: cDetails were printed to the server console and logs, please add that to your bug report.
`
I'm not sure whether if it's terra or mv's problem...

### Steps to reproduce

start server with multiverse and terra installed
type "/mv gens"
get bug
try "/mv create testworld normal -g terra" anway
default world with no generator

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
With the latest Paper, Multiverse Core and Terraform Generator I cannot reproduce this issue
