### ISSUE TITLE
[Bug]: Minecraft-Region-Fixer

### ISSUE THREAD

**Issue by Geant200** [Multiverse/Multiverse-Core#2812]
### `/mv version -p` output

https://bit.ly/3EfNkQ1

### Server logs

https://paste.gg/p/anonymous/c40eb6526b9c4fb987942b6fd0b715d4

### Server Version

```shell
This server is running CraftBukkit version 3605-Spigot-6198b5a-f43634a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)
```

### Bug Description

When I type the command /mv import redstone2022 normal it won't and gives me the following message.

```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: .\redstone2022\session.lock
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.createWorld(CraftServer.java:1059)
at org.bukkit.Bukkit.createWorld(Bukkit.java:672)
at org.bukkit.WorldCreator.createWorld(WorldCreator.java:405)
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288)
at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:131)
at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:818)
at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:419)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:395)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197)
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.AccessDeniedException: .\redstone2022\session.lock
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
at net.minecraft.util.SessionLock.a(SourceFile:37)
at net.minecraft.world.level.storage.Convertable$ConversionSession.<init>(Convertable.java:402)
at net.minecraft.world.level.storage.Convertable.createAccess(Convertable.java:327)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.createWorld(CraftServer.java:1057)
... 19 more
```

```
[Multiverse-Core]: The world 'redstone2022' could NOT be loaded because it contains errors and is probably corrupt!
[Multiverse-Core]: Try using Minecraft Region Fixer to repair your world! 'redstone2022'
[Multiverse-Core]: https://github.com/Fenixin/Minecraft-Region-Fixer
[Multiverse-Core]: Failed to Create/Load the world 'redstone2022'

```

I can create a new world but I can't import a new world made locally.

I thank you in advance.

### Steps to reproduce

/mv import redstone2022 normal

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
Try deleting session.lock file in that world directory

**Comment by NeverGrowUp** [comment]
Check the security/permissions for the whole directory...
