### ISSUE TITLE
[Bug]: [Multiverse-Core] The world 'Spawn' could NOT be loaded because it contains errors and is probably corrupt!

### ISSUE THREAD

**Issue by CubixTube** [Multiverse/Multiverse-Core#2816]
### `/mv version -p` output

Version info dumped here: Error posting to service

### Server logs

Error in logs - [02:32:29] [Server thread/ERROR]: [Multiverse-Core] The world 'amongus' could NOT be loaded because it contains errors and is probably corrupt! [02:32:29] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'amongus' [02:32:29] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer [02:32:29] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'amongus'

### Server Version

```shell
CraftBukkit version 3445-spigot-fb0dd5f-05a38da (MC: 1.18.2) (Implementing API version 1.18.2-Ro.1-SNAPSHOT)
```

### Bug Description

I just got the plugin and did     /mv hub normal create -t flat     3 times and all three times it said failed

I can delete the worlds 
they are unloaded 
and i dont know what to do

### Steps to reproduce

idk
/mv delete 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
Full logs will help. There is probably more to that error than you have copied.

**Comment by CubixTube** [comment]
> Full logs will help. There is probably more to that error than you have copied.

This is as much as I can scroll to after a restart is is this enough?
[03:01:03] [Worker-Main-2/INFO]: Preparing spawn area: 81%
[03:01:03] [Worker-Main-2/INFO]: Preparing spawn area: 81%
[03:01:03] [Server thread/INFO]: Time elapsed: 14490 ms
[03:01:04] [Server thread/INFO]: [skript-npc] Enabling skript-npc v0.1.2
[03:01:04] [Server thread/INFO]: [skript-npc] skript-npc is warming up...
[03:01:04] [Server thread/INFO]: [skript-npc] Metrics are enabled.
[03:01:04] [Server thread/WARN]: [skript-npc] Loaded class ch.njol.skript.Skript from Skript v2.6.4 which is not a depend or softdepend of this plugin.
[03:01:04] [Server thread/ERROR]: [skript-npc] Skript is not accepting registrations!
[03:01:04] [Server thread/INFO]: [skript-npc] Finished loading.
[03:01:04] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[03:01:04] [Server thread/WARN]: [PlaceholderAPI] Loaded class com.viaversion.viaversion.api.type.Type from ViaVersion v4.5.1 which is not a depend or softdepend of this plugin.
[03:01:04] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[03:01:04] [Server thread/INFO]: [MinehutAnalytics] Enabling MinehutAnalytics v1.0-SNAPSHOT
[03:01:04] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.5.1
[03:01:04] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
[03:01:04] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[03:01:04] [Server thread/INFO]: [Multiverse-Core] ?aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:01:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1033)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:671)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:407)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:614)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:416)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1013)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
[03:01:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] The world 'Hub' could NOT be loaded because it contains errors and is probably corrupt!
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Hub'
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[03:01:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1033)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:671)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:407)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:614)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:416)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1013)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
[03:01:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] The world 'amongus' could NOT be loaded because it contains errors and is probably corrupt!
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'amongus'
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[03:01:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1033)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:671)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:407)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[03:01:04] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[03:01:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:614)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:416)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1013)
[03:01:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
[03:01:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] The world 'Spawn' could NOT be loaded because it contains errors and is probably corrupt!
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Spawn'
[03:01:04] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[03:01:04] [Server thread/INFO]: [Multiverse-Core] 1 - World(s) loaded.
[03:01:04] [Server thread/WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[03:01:04] [Server thread/INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[03:01:04] [Server thread/INFO]: [ItemEdit] Enabling ItemEdit v3.0.7
[03:01:04] [Server thread/INFO]: [ItemEdit] Unable to hook into Vault
[03:01:04] [Server thread/INFO]: [ItemEdit] Hooking into PlaceholderApi
[03:01:04] [Server thread/WARN]: [ItemEdit] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.11.2 which is not a depend or softdepend of this plugin.
[03:01:04] [Server thread/INFO]: [ItemEdit] Hooked into PlaceHolderAPI:
[03:01:04] [Server thread/INFO]: [ItemEdit] placeholders:
[03:01:04] [Server thread/INFO]: [ItemEdit]   %itemedit_amount_<{itemid}>_[{slot}]_[{player}]%
[03:01:04] [Server thread/INFO]: [ItemEdit]     shows how many itemid player has on slot
[03:01:04] [Server thread/INFO]: [ItemEdit]     <{itemid}> for item id on serveritem
[03:01:04] [Server thread/INFO]: [ItemEdit]     [{slot}] for the slot where the item should be counted, by default inventory
[03:01:04] [Server thread/INFO]: [ItemEdit]       Values: inventory, equip, inventoryandequip, hand, offhand, head, chest, legs, feet
[03:01:04] [Server thread/INFO]: [ItemEdit]     [{player}] for the player, by default self
[03:01:04] [Server thread/INFO]: [ItemEdit]     example: %itemedit_amount_{my_item_id}_{hand}%
[03:01:04] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: itemedit [1.0]
[03:01:04] [Server thread/INFO]: [ItemEdit] # Enabled (took 153 ms)
[03:01:04] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.7+216b061
[03:01:04] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[03:01:04] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[03:01:04] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[03:01:04] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[03:01:04] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[03:01:04] [Server thread/INFO]: [WorldGuard] Loading region data...
[03:01:05] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2807)
[03:01:05] [Server thread/INFO]: [Citizens] Loading external libraries
[03:01:05] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: citizensplaceholder [1.0.0]
[03:01:05] [Server thread/INFO]: [Skript] Enabling Skript v2.6.4
[03:01:06] [Thread-10/INFO]: [Skript] You're currently running the latest stable version of Skript.
[03:01:15] [Server thread/INFO]: [Skript] Loaded 143215 aliases in 9557ms
[03:01:16] [Server thread/INFO]: [Skript]  ~ created by & ? Peter G?ttinger aka Njol ~
[03:01:16] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v2.15.1
[03:01:16] [Server thread/INFO]: [Shopkeepers] Citizens found: Enabling NPC shopkeepers.
[03:01:16] [Server thread/INFO]: [Shopkeepers] Loading the data of 8 shopkeepers ...
[03:01:16] [Server thread/INFO]: [TAB] Enabling TAB v3.2.0
[03:01:16] [Server thread/INFO]: [TAB] Server version: 1.18.2 (v1_18_R2)
[03:01:16] [Server thread/INFO]: [TAB] Loaded NMS hook in 20ms
[03:01:16] [Server thread/INFO]: [TAB] Enabled in 119ms
[03:01:16] [Server thread/INFO]: [skript-gui] Enabling skript-gui v1.3
[03:01:16] [Server thread/INFO]: [Skript] Missing version in default.lang
[03:01:16] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:01:16] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[03:01:16] [Server thread/INFO]: Done (29.040s)! For help, type "help"
[03:01:16] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.18.2 (758)
[03:01:17] [Server thread/INFO]: [Skript] Loading variables...
[03:01:17] [Server thread/INFO]: [Skript] Loaded 4 variables in 0.0 seconds
[03:01:17] [Server thread/INFO]: [Skript] Line 4: (ConcreteStickWand.sk)
[03:01:17] [Server thread/INFO]:     indentation error: expected 2 tabs, but found 8 spaces
[03:01:17] [Server thread/INFO]:     Line: add "{Invisible:1b}" to nbt of last spawned armor stand
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 5: (Glassbreaktestai.sk)
[03:01:17] [Server thread/INFO]:     invalid line - all code has to be put into triggers
[03:01:17] [Server thread/INFO]:     Line: pet My Pet
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 7: (Glassbreaktestai.sk)
[03:01:17] [Server thread/INFO]:     invalid line - all code has to be put into triggers
[03:01:17] [Server thread/INFO]:     Line: name: Fluffy
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 8: (Glassbreaktestai.sk)
[03:01:17] [Server thread/INFO]:     invalid line - all code has to be put into triggers
[03:01:17] [Server thread/INFO]:     Line: health: 10
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 12: (Glassbreaktestai.sk)
[03:01:17] [Server thread/INFO]:     Can't understand this event: 'on spawn of My Pet'
[03:01:17] [Server thread/INFO]:     Line: on spawn of My Pet:
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 17: (Glassbreaktestai.sk)
[03:01:17] [Server thread/INFO]:     Can't understand this event: 'on death of My Pet'
[03:01:17] [Server thread/INFO]:     Line: on death of My Pet:
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 2: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     Can't understand this condition/effect: player has clicked on a sign named "GUI"
[03:01:17] [Server thread/INFO]:     Line: player has clicked on a sign named "GUI"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 3: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     Can't understand this condition/effect: open a GUI with the title "My GUI"
[03:01:17] [Server thread/INFO]:     Line: open a GUI with the title "My GUI"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 4: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     You can't use 'the GUI' outside of a GUI make or open/close section.
[03:01:17] [Server thread/INFO]:     Line: set the size of the GUI to 3 rows
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 5: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     You can't use 'the GUI' outside of a GUI make or open/close section.
[03:01:17] [Server thread/INFO]:     Line: set the 12th slot of the GUI to a stone sword with the name "Stony Sword"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 6: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     You can't use 'the GUI' outside of a GUI make or open/close section.
[03:01:17] [Server thread/INFO]:     Line: set the 13th slot of the GUI to a diamond sword with the name "Diamondy Sword"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 7: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     You can't use 'the GUI' outside of a GUI make or open/close section.
[03:01:17] [Server thread/INFO]:     Line: set the 14th slot of the GUI to a feather with the name "Feathery Feather"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 8: (Guitest.sk)
[03:01:17] [Server thread/INFO]:     You can't use 'the GUI' outside of a GUI make or open/close section.
[03:01:17] [Server thread/INFO]:     Line: set the 16th slot of the GUI to a red wool block named "-->"
[03:01:17] [Server thread/INFO]:  
[03:01:17] [Server thread/INFO]: [Skript] Line 5: (SpawnNPC.sk)
[03:01:17] [Server thread/INFO]:     Can't understand this condition/effect: add "{Silent:1b,NoAI:1b,Invulnerable:1}" to nbt of spawned villager
[03:01:17] [Server thread/INFO]:     Line: add "{Silent:1b,NoAI:1b,Invulnerable:1}" to nbt of spawned villager
[03:01:17] [Server thread/INFO]:  
[03:01:18] [Server thread/INFO]: [Skript] Loaded 10 scripts with a total of 33 triggers and 4 commands in 1.63 seconds
[03:01:18] [Server thread/INFO]: [Skript] Finished loading.
[03:01:18] [Server thread/INFO]: 0 placeholder hook(s) registered!
[03:01:19] [Server thread/INFO]: [Citizens] Loaded 8 NPCs.
[03:01:19] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!

**Comment by zax71** [comment]
Here are some steps to give us full logs 

Your logs can be found in `/logs/latest.log` 

After you open that file you will see lots of text, copy and paste that with CTRL+C and CTRL+V it in https://mclo.gs/ , just click save and send the link to the page it sends you to.

**Comment by Cabronoso** [comment]
I am having this issue at the moment as well. 

> [03:55:24] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
[03:55:24] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[03:55:24] [Server thread/INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[03:55:24] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:55:24] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[03:55:24] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'NewWorld1' - Env: NORMAL - Type: NORMAL & seed: -2549039763105106918
[03:55:24] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'NewWorld1_nether' - Env: NETHER - Type: NORMAL & seed: -2549039763105106918
[03:55:24] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'NewWorld1_the_end' - Env: THE_END - Type: NORMAL & seed: -2549039763105106918
[03:55:24] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[03:55:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.createWorld(CraftServer.java:1055)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:672)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:405)
[03:55:24] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[03:55:24] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[03:55:24] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[03:55:24] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[03:55:24] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539)
[03:55:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453)
[03:55:24] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587)
[03:55:24] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412)
[03:55:24] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[03:55:24] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[03:55:24] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[03:55:24] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:55:24] [Server thread/ERROR]: [Multiverse-Core] The world 'Summer_Vacation' could NOT be loaded because it contains errors and is probably corrupt!
[03:55:24] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Summer_Vacation'
[03:55:24] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[03:55:24] [Server thread/INFO]: [Multiverse-Core] 3 - World(s) loaded.
[03:55:24] [Server thread/WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[03:55:24] [Server thread/INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

**Comment by Lildirt** [comment]
I suspect something outside of MV's control has happened here and there may be some credibility to the world errors.
These errors are bubbling up from the server itself and not from MV's management.

The stacktrace originates from Bukkit and the environment exception (and warning) isn't something reported by MV.

As this seems to be world data related (and not region data), you may be able to delete certain dat files to get the world to load (e.g., `uid.dat`, `level.dat`). Obviously, back up your world before trying something like this and it might have some implications. Region Fixer is also worth trying before that nuclear option, but it may or may not try to touch level data (no idea).

**Either way, I highly doubt this is a Multiverse issue**, unless someone else can prove otherwise. Multiverse doesn't really have much involvement in the actual loading process of a world, like parsing the environment. Loading a world through Bukkit world management is a fairly hands-off process and even feeding it bad data from our end (e.g., wrong environment) just results in it loading the options from the level data and not from our parameters.

**Comment by averwhy** [comment]
I'm encountering this bug as well, its extremely frustrating that MV refuses to load a world even though its entirely compatible. I'm trying to load a world called `world_arks` but it shows with that 'could NOT be loaded' error

https://paste.gg/p/anonymous/610a6a71301f4d86a9e502ae3aaa238c

I've used the region fixer, loaded it on singleplayer on the same version, but to no luck. Wtf is happening?

**Comment by ImCardiaK** [comment]
Hello!

I have the same issue! With a 1.20-compatible world and Multiverse Plugins version 4.3.12
How can I fix the problem?

(I used "Minecraft Region Fixer" as mentioned in the error message below. But the issue persists!)
The error message is the same as the one sent at the beginning of this thread.

Thank you!

**Comment by benwoo1110** [comment]
If the world is corrupted - we can't do much

**Comment by zax71** [comment]
Can you please send your **full** server logs on https://mclo.gs

<details>
    <summary>How do I do that?</summary>

    1. Copy the file in `/logs/latest.log`
    2. Copy the contents of that file with `Ctrl`+`A` then `Ctrl`+`C`
    3. Paste that in the large text box on https://mclo.gs with `Ctrl`+`V`
    4. Press save
    5. Copy the address of the website that it redirects you to
    6. Paste that here so that we can see it!


</details>
