### ISSUE TITLE
[Error]: Error Massage in my Console-Log.

### ISSUE THREAD

**Issue by BAT0exe** [Multiverse/Multiverse-Core#3076]
### `/mv version -p` output

v4.3.12

### Server logs

https://mclo.gs/WyJ4Mfd 

### Server Version

```shell
Server Version: 4149-Spigot-e2c1eee-4e7d749 (MC: 1.20.6) (LatestBuild)
```

### Bug Description

I just saw this error message in my console log and just wanted to share it.
Apart from the fact that I can't import worlds onto my server, there are no other bugs.

### Steps to reproduce

1. Start the Server. (Error message appears in the log.)

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
This normally means that the world file has some kind of an issue. Try loading it in singleplayer (the same version as your server) and then re-importing it

**Comment by BAT0exe** [comment]
That's exactly the problem there. I created a world in Singleplayer, and then tried to import this World onto the server.

**`Here is a litte overview of the Massage from the Log`:**`
 java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.ordinal()" because the return value of "org.bukkit.WorldCreator.environment()" is null
[17:41:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.createWorld(CraftServer.java:1095)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:736)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:430)
[17:41:01] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[17:41:01] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[17:41:01] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[17:41:01] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[17:41:01] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541)
[17:41:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455)
[17:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634)
[17:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[17:41:01] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265)
[17:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
[17:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
[17:41:01] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[17:41:01] [Server thread/ERROR]: [Multiverse-Core] The world 'Spawnwelt' could NOT be loaded because it contains errors and is probably corrupt!
[17:41:01] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Spawnwelt'
[17:41:01] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[17:41:01] [Server thread/INFO]: [Multiverse-Core] 4 - World(s) loaded.
[17:41:01] [Server thread/WARN]: [Multiverse-Core] Buscript failed to load! The script command will be

**Comment by NeverGrowUp** [comment]
Delete the `session.lock` file in your world directory that you are importing

**Comment by BAT0exe** [comment]
> Delete the `session.lock` file in your world directory that you are importing

Hello, thank you in advance for your idea.
I tried this with the `session.lock,` but unfortunately that didn't work either. :(

_I'm still trying to import a world, or maybe someone has the solution.._

**Comment by NeverGrowUp** [comment]
Show new logs with `session.lock` removed and new attempt at importing.

**Comment by BAT0exe** [comment]
> Show new logs with `session.lock` removed and new attempt at importing.

There's a lot in there, but it looks like that wasn't the problem..
maybe you see something wrong in it?
https://mclo.gs/g5CYeGk

**Comment by NeverGrowUp** [comment]
Either you didn't remove `session.lock` or server doesn't have permission to read/write to that world directory.

**Comment by BAT0exe** [comment]
> Either you didn't remove `session.lock` or server doesn't have permission to read/write to that world directory.

I deleted the session.lock file... 
it will probably be the case that the server doesn't have read or write permission... I'll have to check this.. 
but, i just have to see how I can give the server permission to do this first

and thank you for helping me with this <3

**Comment by NeverGrowUp** [comment]
With Linux, use chmod 664. 
For windows, not to sure. Think you can right-click on the world directory and change security perms.

**Comment by BAT0exe** [comment]
This probably sounds stupid, but I have to do this in the root console of the server and not in the Minecraft server console, right? or can I pass this as a java argument?
I'm absolutely a beginner... I've only ever rented MC servers before, and now I'm trying to get a dedicated server up and running...

**Comment by NeverGrowUp** [comment]
Yes at root console.

**Comment by BAT0exe** [comment]
Hello, short feedback:
it was actually due to the permissions. I have now set my file manager how it should upload.  👍 
**[Problem Solved]**
