### ISSUE TITLE
[Idea]: Excuse me, can you add the weather or time to lock a certain world?

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [Multiverse/Multiverse-Core#3092]
### Describe the feature

I hope every world can have different gamerule, among which weather and time are the most needed.

For example, when I create a world to simulate outer space, I need to disable its weather and lock it as night, and it can't affect the normal passage of time in other worlds.

### How is the feature useful to all Multiverse users?

VERY GOOOOD

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Maddin-M** [comment]
I wrote plugins for this exact thing: [MultiTime](https://www.spigotmc.org/resources/multitime.90642/) and [MuiltiWeather](https://www.spigotmc.org/resources/multiweather.91452/)

**Comment by zax71** [comment]
This is already a feature if I’m not mistaken. `/mv gamerule` exists and I’m pretty sure the vanilla time commands are per world

**Comment by Maddin-M** [comment]
> This is already a feature if I’m not mistaken. `/mv gamerule` exists and I’m pretty sure the vanilla time commands are per world

At the time of me writing the plugins, the vanilla time command affected all worlds. But yes, `/mv gamerule` would do the same.

**Comment by MinecraftEarthVillage** [comment]
> 我为这个东西编写了插件：[MultiTime](https://www.spigotmc.org/resources/multitime.90642/) 和 [MuiltiWeather](https://www.spigotmc.org/resources/multiweather.91452/)

我的世界服务器有两个插件没有正确载入，请告诉我解决方法
[00:19:07] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/[多世界时间]MultiTime-1.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:320) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:396) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:222) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[00:19:14] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/[锁定天气]MultiWeather-1.3.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:320) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:396) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[forge-1.20.1-47.3.5-universal.jar%23251!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:222) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23246!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Maddin-M** [comment]
Try an older version. `MultiTime 1.3.2` worked for me on MC 1.20.1.

**Comment by benwoo1110** [comment]
as mentioned, use `/mv gamerule` command
