### ISSUE TITLE
[Bug]: EntityCreatePortalEvent

### ISSUE THREAD

**Issue by 5FearL1fe** [Multiverse/Multiverse-Core#3096]
### `/mv version -p` output

https://paste.gg/p/anonymous/ed96f0c9803a4d63b62d10ce2d284259

### Server logs

https://paste.gg/p/anonymous/48cc924bf3d94c318028791fc9378476

### Server Version

```shell
/version
[14:32:03 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-51-789a267 (MC: 1.21.1)
>
```

### Bug Description

Idk, i keep getting the warning about multiverse, and then after a little while of the server being on, i get all these weird humoungous longs warn codes and i have no idea what it is. I know about the voting stuff, but its not that, ive only just recently added it and havent finished setting it up, but the problems been going on since before then.

### Steps to reproduce

1. start server
2. everything fine
3. warn about multivers
4. server loads more
5. server is done loading
6. after a while, huge random warn codes appear

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
I looked at the server logs you send, I don't see any "huge random warning". Could you pin point which warning lines you are referring to?

**Comment by DoomSlayer-Gaming-YT** [comment]
No the warnings havent appeared yet, but they do after a short time. I can add the warn in another comment if you like, when it starts showing up.

**Comment by DoomSlayer-Gaming-YT** [comment]
Oh, heres the first warn so far, it goes like 2 or 3 small, then this HUGE one
[14:39:01 WARN]: io.netty.handler.timeout.ReadTimeoutException

**Comment by benwoo1110** [comment]
Yes please send those warning, thanks!

**Comment by DoomSlayer-Gaming-YT** [comment]
Heres the next, ignore the votifier one, ik about that, thats fine, but after the warn, i believe its the big one
[15:21:41 ERROR]: [Votifier] Unable to process vote from /205.210.31.19:57812
com.vexsoftware.votifier.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[15:37:11 WARN]: io.netty.handler.timeout.ReadTimeoutException

**Comment by DoomSlayer-Gaming-YT** [comment]
Ah, heres the big code, i knew it'd do it again...
[03:11:06 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[03:11:06 WARN]: Packet Type: CLIENT_INTENTION, Type: StringType, Index: 2, Data: [{VarInt: 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$$Lambda/0x00007ff7a107d830, Packet ID: 0
[03:11:06 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[03:11:06 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:114)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:11:06 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[03:11:06 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[03:11:06 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[03:11:06 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:11:06 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:11:06 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[03:11:06 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[03:11:06 WARN]: Packet Type: CLIENT_INTENTION, Type: StringType, Index: 2, Data: [{VarInt: 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$$Lambda/0x00007ff7a107d830, Packet ID: 0
[03:11:06 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[03:11:06 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[03:11:06 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[03:11:06 WARN]:        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:185)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocols.base.BaseProtocol.lambda$registerPackets$0(BaseProtocol.java:60)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocols.base.BaseProtocol.transform(BaseProtocol.java:152)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:318)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:53)
[03:11:06 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:33)
[03:11:06 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[03:11:06 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[03:11:06 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:114)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:11:06 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:11:06 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:11:06 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:11:06 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[03:11:06 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[03:11:06 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[03:11:06 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:11:06 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:11:06 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[04:15:30 WARN]: io.netty.handler.timeout.ReadTimeoutException
[04:39:34 WARN]: io.netty.handler.timeout.ReadTimeoutException
[07:39:56 WARN]: io.netty.handler.timeout.ReadTimeoutException
[08:29:12 INFO]: [Vault] Checking for Updates ... 
[08:29:12 INFO]: [Vault] No new version available
[08:42:51 WARN]: io.netty.handler.timeout.ReadTimeoutException
[09:26:18 WARN]: io.netty.handler.timeout.ReadTimeoutException
[09:39:21 WARN]: io.netty.handler.timeout.ReadTimeoutException
[09:55:17 WARN]: io.netty.handler.timeout.ReadTimeoutException
[11:18:35 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:18:35 WARN]: Packet Type: CLIENT_INTENTION, Type: StringType, Index: 2, Data: [{VarInt: 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$$Lambda/0x00007ff7a107d830, Packet ID: 0
[11:18:35 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[11:18:35 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:114)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:18:35 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[11:18:35 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[11:18:35 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[11:18:35 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:18:35 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:18:35 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[11:18:35 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:18:35 WARN]: Packet Type: CLIENT_INTENTION, Type: StringType, Index: 2, Data: [{VarInt: 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$$Lambda/0x00007ff7a107d830, Packet ID: 0
[11:18:35 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[11:18:35 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[11:18:35 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[11:18:35 WARN]:        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:185)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocols.base.BaseProtocol.lambda$registerPackets$0(BaseProtocol.java:60)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocols.base.BaseProtocol.transform(BaseProtocol.java:152)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:318)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:53)
[11:18:35 WARN]:        at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:33)
[11:18:35 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[11:18:35 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[11:18:35 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:114)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:18:35 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[11:18:35 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:18:35 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:18:35 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[11:18:35 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[11:18:35 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[11:18:35 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:18:35 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:18:35 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by NeverGrowUp** [comment]
ViaVersion....

**Comment by 5FearL1fe** [comment]
what do you mean?

**Comment by NeverGrowUp** [comment]
That whole stack relates to ViaVersion and not multiverse

**Comment by 5FearL1fe** [comment]
i got a warning about multiverse, and then that huge stuff pops up, but if its viaversion, then whys it doing it?

**Comment by NeverGrowUp** [comment]
You didn't paste the multiverse warning/message, so only going by what you have provided.

**Comment by 5FearL1fe** [comment]
i did? its in the startup log?

**Comment by NeverGrowUp** [comment]
If you are referring to `§aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.` then the last 5 words are the answer.

Your issue resides with ViaVersion

**Comment by 5FearL1fe** [comment]
Do you know what the ViaVersion problem is?

**Comment by zax71** [comment]
Ask ViaVersion support

**Comment by 5FearL1fe** [comment]
ok thanks!

**Comment by zax71** [comment]
Can I close this issue?
