### ISSUE TITLE
[Support]: Corrupted world

### ISSUE THREAD

**Issue by kolyax** [Multiverse/Multiverse-Core#3111]
### `/mv version -p` output

> mv version -p [19:40:55 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.1-b861 [19:40:55 INFO]: [Multiverse-Core] Bukkit Version: git-Paper-790 (MC: 1.16.5) [19:40:55 INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@159944696":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-6"}}, {"MVWorld@1665144447":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-5"}}, {"MVWorld@1896711768":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-2"}}, {"MVWorld@2089616319":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-1"}}, {"MVWorld@834122905":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-4"}}, {"MVWorld@1378336574":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"Bedwars-factory"}}, {"MVWorld@1325784164":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"bedwars-3"}}, {"MVWorld@1535225536":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"creative-2"}}, {"MVWorld@1470028373":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"creative-3"}}, {"MVWorld@951013847":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Bedwars-loby"}}, {"MVWorld@1504201818":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@260640257":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@786706903":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@1820851253":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"creative-1"}}, {"MVWorld@2010556259":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"creative-lobby"}}, {"MVWorld@812140190":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"gonki-nalodkah"}}] [19:40:55 INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 0 [19:40:55 INFO]: [Multiverse-Core] Economy being used: Simple Item Economy [19:40:55 INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms) [19:40:55 INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9) [19:40:55 INFO]: [Multiverse-Core]   enforceaccess: false [19:40:55 INFO]: [Multiverse-Core]   prefixchat: false [19:40:55 INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat% [19:40:55 INFO]: [Multiverse-Core]   useasyncchat: true [19:40:55 INFO]: [Multiverse-Core]   teleportintercept: true [19:40:55 INFO]: [Multiverse-Core]   firstspawnoverride: true [19:40:55 INFO]: [Multiverse-Core]   displaypermerrors: true [19:40:55 INFO]: [Multiverse-Core]   enablebuscript: true [19:40:55 INFO]: [Multiverse-Core]   globaldebug: 0 [19:40:55 INFO]: [Multiverse-Core]   silentstart: false [19:40:55 INFO]: [Multiverse-Core]   messagecooldown: 5000 [19:40:55 INFO]: [Multiverse-Core]   version: 2.9 [19:40:55 INFO]: [Multiverse-Core]   firstspawnworld: world [19:40:55 INFO]: [Multiverse-Core]   teleportcooldown: 1000 [19:40:55 INFO]: [Multiverse-Core]   defaultportalsearch: true [19:40:55 INFO]: [Multiverse-Core]   portalsearchradius: 128 [19:40:55 INFO]: [Multiverse-Core]   autopurge: true [19:40:55 INFO]: [Multiverse-Core] Special Code: FRN002 [19:40:55 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api-ssl.bitly.com/v4/shorten [19:40:55 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) [19:40:55 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) [19:40:55 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) [19:40:55 WARN]:        at com.onarandombox.MultiverseCore.utils.webpaste.HttpAPIClient.exec(HttpAPIClient.java:109) [19:40:55 WARN]:        at com.onarandombox.MultiverseCore.utils.webpaste.BitlyURLShortener.shorten(BitlyURLShortener.java:49) [19:40:55 WARN]:        at com.onarandombox.MultiverseCore.commands.VersionCommand.postToService(VersionCommand.java:211) [19:40:55 WARN]:        at com.onarandombox.MultiverseCore.commands.VersionCommand.access$000(VersionCommand.java:36) [19:40:55 WARN]:        at com.onarandombox.MultiverseCore.commands.VersionCommand$1.run(VersionCommand.java:174) [19:40:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) [19:40:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [19:40:55 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [19:40:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [19:40:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [19:40:55 WARN]:        at java.lang.Thread.run(Unknown Source) [19:40:55 INFO]: [Multiverse-Core] Version info dumped here: https://paste.gg/54145ad6d3ee47eaae1ab5c726a4afff

### Server logs

https://pastebin.com/1YhGsuvD

### Server Version

```shell
This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Bug Description

I'm writing `/mvtp bedwars-6`

### Steps to reproduce

створити багато світів 
![Screenshot 2024-10-05 193644](https://github.com/user-attachments/assets/1844e2bb-ff4e-45be-9180-b5caecb24e4d)
load into their saves and try to write `/mv tp` last world

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Your world seems to be corrupted

**Comment by kolyax** [comment]
А забув сказати сгенерований світ працює а завантажений ні

**Comment by zax71** [comment]
That is most likely a corrupted world then, try loading it in singleplayer first and then importing it in to the server
