### ISSUE TITLE
[Bug]: [Bug]: It doesn't allow me to go to other worlds when using /mv tp 

### ISSUE THREAD

**Issue by SrMaruchans** [Multiverse/Multiverse-Core#3134]
### `/mv version -p` output

https://paste.gg/p/anonymous/7b2e82a1857d4753bd7a8f4340ee02cb

### Server logs

https://gist.github.com/SrMaruchans/4defd7348d6b2925c33859bb66804bd9

### Server Version

```shell
1.21.3
```

### Bug Description

Cuando intento ir a un mundo con /mv tp me mara un error en pantalla, deja al personaje cayendo del mundo infinitamente y no deja usar más comandos, en ma consola aparece un error de bug. 
![IMG_0829](https://github.com/user-attachments/assets/16467873-dbdc-4224-9102-f420a2999fc9)
![IMG_0828](https://github.com/user-attachments/assets/1e804806-14ca-4a4a-8c53-a66d675c52f0)
![IMG_0832](https://github.com/user-attachments/assets/786139d8-bb89-4eb0-b3a7-bb2539a44672)

[latest.log](https://github.com/user-attachments/files/17941279/latest.log)

### Steps to reproduce

1. escribo el comando /mv tp mundo
2. Me marca en rojo en el chat del Minecraft un mensaje "An internal error ocurre when attempting to perform this command. Details were printed tobthe server console and Logs, please add that to your bug report. 
3. Entro a consola y me rale un error de bug en amarillo. 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Please send the full logs, not just part of it and screenshots. thanks!

**Comment by SrMaruchans** [comment]
> Por favor envíe los registros completos, no sólo parte de ellos y capturas de pantalla. ¡Gracias!

El registro completo esta en el link, ahí lo mande.

**Comment by SrMaruchans** [comment]
> Please send the full logs, not just part of it and screenshots. thanks!

Intento poner completo los Logs pero no me deja, intentaré de otra forma

**Comment by SrMaruchans** [comment]
> Please send the full logs, not just part of it and screenshots. thanks!

Adjunto el archivo Log 

[latest.log](https://github.com/user-attachments/files/17941273/latest.log)

**Comment by SrMaruchans** [comment]
> Por favor envíe los registros completos, no sólo parte de ellos y capturas de pantalla. ¡Gracias!

[19:16:06] [Server thread/INFO]: Maruchans issued server command: /mv tp world
[19:16:06] [Server thread/WARN]: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
[19:16:06] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeInstance.addModifier(AttributeInstance.java:80)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifier(AttributeInstance.java:106)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifiers(AttributeInstance.java:112)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeMap.lambda$assignPermanentModifiers$7(AttributeMap.java:127)
[19:16:06] [Server thread/WARN]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$1.forEach(Object2ObjectOpenHashMap.java:1188)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeMap.assignPermanentModifiers(AttributeMap.java:124)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.restoreFrom(ServerPlayer.java:2353)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:789)
[19:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1515)
[19:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1370)
[19:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:246)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:338)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:152)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[19:16:06] [Server thread/WARN]: 	at multiverse-core-4.3.14.jar//com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[19:16:06] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:16:06] [Server thread/WARN]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[19:16:06] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:363)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2319)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2293)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1619)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1596)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1589)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1540)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1550)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1386)
[19:16:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:342)
[19:16:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by zax71** [comment]
> > Please send the full logs, not just part of it and screenshots. thanks!
> 
> Adjunto el archivo Log
> 
> [latest.log](https://github.com/user-attachments/files/17941273/latest.log)

Uploaded log: https://mclo.gs/uJ25rto

**Comment by zax71** [comment]
That is not a full log, can you please send your **full** server logs on https://mclo.gs

<details>
    <summary>How do I do that?</summary>

    1. Copy the file in `/logs/latest.log`
    2. Copy the contents of that file with `Ctrl`+`A` then `Ctrl`+`C`
    3. Paste that in the large text box on https://mclo.gs with `Ctrl`+`V`
    4. Press save
    5. Copy the address of the website that it redirects you to
    6. Paste that here so that we can see it!


</details>

**Comment by zero-but-one** [comment]
Yes, I have encountered the same problem recently. An error will occur if I teleport between multiple worlds. If there is any information and logs that I can provide, I will definitely try my best to assist you.

**Comment by SrMaruchans** [comment]
Ya lo solucione! Tuve que reinstalar mi servidor, nunca me respondieron a tiempo después de mi ultimo mensaje.

**Comment by jfoucher** [comment]
> Ya lo solucione! Tuve que reinstalar mi servidor, nunca me respondieron a tiempo después de mi ultimo mensaje. Desde el 29 de Noviembre, ya poco más de un mes, vaya soporte de MV! Muy pésimo.

No hay soporte. Dan su codigo totalmente gratis al mundo entero. Si no te funciona no lo uses

There is no support. They give their code completely free to the whole world. If it does not work for you then stop using it.

**Comment by benwoo1110** [comment]
This is most likely a server software issue or things that mess with low level nms.
