### ISSUE TITLE
import world failed

### ISSUE THREAD

**Issue by acaldra55** [Multiverse/Multiverse-Core#915]
Hello, 
i am new to multiverse when i try to import a world it always fail here is the log: 

```
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.ServerConnection.b(SourceFile:35)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:810)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:828)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:915)
18.10 12:17:19 [Server] SEVERE at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
18.10 12:17:19 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
18.10 12:17:19 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18.10 12:17:19 [Server] SEVERE at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:859)
18.10 12:17:19 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
18.10 12:17:19 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
18.10 12:17:19 [Server] SEVERE at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
18.10 12:17:19 [Server] SEVERE at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
18.10 12:17:19 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:226)
18.10 12:17:19 [Server] SEVERE at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:392)
18.10 12:17:19 [Server] SEVERE at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
18.10 12:17:19 [Server] SEVERE at org.bukkit.Bukkit.createWorld(Bukkit.java:155)
18.10 12:17:19 [Server] SEVERE at org.bukkit.craftbukkit.CraftServer.createWorld(CraftServer.java:692)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.ServerNBTManager.<init>(SourceFile:16)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.WorldNBTStorage.<init>(WorldNBTStorage.java:40)
18.10 12:17:19 [Server] SEVERE at net.minecraft.server.WorldNBTStorage.h(WorldNBTStorage.java:46)
18.10 12:17:19 [Server] SEVERE at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
18.10 12:17:19 [Server] SEVERE at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
18.10 12:17:19 [Server] SEVERE at java.io.FileOutputStream.open(Native Method)
18.10 12:17:19 [Server] SEVERE java.io.FileNotFoundException: ./arena1/session.lock (Permission denied)
18.10 12:17:19 [Server] INFO [Multiverse-Core] Loading World & Settings - 'arena1' - Env: NORMAL - Type: null
18.10 12:17:19 [Server] INFO acaldra55: Starting import of world 'arena1'...
```

How can i fix this? also using multverse 2.5 with the latest craftbukkit
Thank you

**Comment by HighRezMC** [comment]
Hm... This is happening to me to. Sorry i know this is 2 and 1/2 years later, but im still wondering... how would you do this same thing, just not via SSL?

**Comment by TWSSYesterday** [comment]
I think you mean SSH, and the host would do it for you if you ask them to.

**Comment by skiingrocks111** [comment]
Im having trouble with this also... What user should i be chowning it to? im guessing its because this thread is out dated, but user:group doesn't work.

**Comment by TWSSYesterday** [comment]
:) if you need anymore help @skiingrocks111 just ask :)
